/**
 * L-Mount SVG specification.
 *
 * The Leica/Panasonic/Sigma L-Mount (Leica T, 2014; L-Mount Alliance, 2018): a 20 mm flange focal
 * distance and a 51.6 mm throat. Modeled `base-only` — a single fully-electronic interface (no
 * mechanical couplings); the APS-C (TL) and full-frame (SL) versions are mechanically compatible, so
 * format is not a mount variant. It uses a four-lug bayonet, and distinctively its ten contacts sit
 * at the TOP of the mount (11–1 o'clock) rather than the bottom.
 *
 * Sourced layout: the L-Mount Alliance documents the 20 mm flange distance, 51.6 mm diameter, and
 * four-tab bayonet [lm-official-1]. Wikipedia supplies the ten-contact count [lm-1]; the locking
 * groove at 4:30 and the contact bank across 11–1 o'clock come from the JAPB teardown [lm-2]. Lug
 * spans, the index position, and per-contact clock positions are photo-scaled and flagged in
 * openQuestions.
 */

import type { MountSpecInput } from "../types/mount.js";
import { degListV, dirV, naV, unknownV, v } from "../optics/mount/authoring.js";

const O = ["lm-official-1"]; // L-Mount Alliance
const W = ["lm-1"]; // Wikipedia
const J = ["lm-2"]; // JAPB teardown

const L_MOUNT = {
  mountId: "l-mount",
  displayLabel: "L-Mount",
  projectNote: "Leica/Panasonic/Sigma L-Mount.",
  researchStatus: "researched",
  mvpStatus: "mvp_complete",
  mechanism: "bayonet",
  lockType: "sprung_detent",

  mvp: {
    requiredViews: ["camera_side_front_view", "lens_side_rear_view", "axial_register_schematic"],
    requirementLevels: {
      mvpRequired: ["flange_focal_distance_mm", "nominal_throat_diameter_mm", "camera_mount_outer_diameter_mm"],
      conditionalCoreRequired: ["bayonet_lugs", "lock_pin", "index_mark"],
      variantRequired: ["electrical_contacts"],
      mvpOptional: ["mount_screws"],
      referenceGrade: ["lug_ramp_undercut", "contact_pitch"],
    },
    profileModel: {
      baseProfileId: "l-mount/base",
      selectedMvpProfileId: "l-mount/base",
      variantStrategy: "base_only",
      variantProfiles: [
        {
          profileId: "l-mount/base",
          profileType: "base",
          appliesTo: "all L-Mount lenses and bodies (APS-C TL and full-frame SL), 2014–present",
          adds: [
            "four bayonet lugs",
            "locking pin/notch at 4:30",
            "mounting index",
            "ten-contact electrical block at the top (11–1 o'clock)",
          ],
          removes: ["all mechanical couplings (fully electronic)"],
          changes: [],
          cameraSideOverlayLayers: ["camera-side-variant-electrical"],
          lensSideOverlayLayers: ["lens-side-variant-electrical"],
          status: "researched",
          sourceRefs: [...O, ...W],
        },
      ],
    },
  },

  coreDimensions: {
    flangeFocalDistanceMm: v(20, "official", O),
    nominalThroatDiameterMm: v(51.6, "official", O),
    effectiveClearApertureMm: v(51.6, "official", O),
    cameraMountOuterDiameterMm: v(62, "photo_scaled", J),
    lensMountOuterDiameterMm: v(60, "photo_scaled", J),
    contactCount: v(10, "secondary", W),
  },

  lockGeometry: {
    insertionAngleDeg: v(0, "secondary", W),
    lockAngleDeg: unknownV(W),
    lockRotationDeg: unknownV(W),
    lockRotationDirection: dirV("unknown", "unknown", []),
  },

  cameraSideFeatures: [
    {
      featureId: "body-throat",
      featureType: "body_throat",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(0, "official", O),
      startAngleDeg: v(0, "official", O),
      endAngleDeg: v(360, "official", O),
      innerRadiusMm: v(0, "official", O),
      outerRadiusMm: v(25.8, "official", O),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "51.6 mm throat opening",
    },
    {
      featureId: "body-mount-ring",
      featureType: "mount_ring",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", J),
      startAngleDeg: v(0, "photo_scaled", J),
      endAngleDeg: v(360, "photo_scaled", J),
      innerRadiusMm: v(25.8, "official", O),
      outerRadiusMm: v(31, "photo_scaled", J),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "visible body mount ring",
    },
    {
      featureId: "body-slot-1",
      featureType: "bayonet_receiving_slot",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(45, "photo_scaled", J),
      startAngleDeg: v(28, "photo_scaled", J),
      endAngleDeg: v(62, "photo_scaled", J),
      innerRadiusMm: v(25.8, "photo_scaled", J),
      outerRadiusMm: v(28.8, "photo_scaled", J),
      depthMm: v(2, "photo_scaled", J),
      matesWith: "lens-lug-1",
      shapeNotes: "four-lug bayonet [lm-2]",
    },
    {
      featureId: "body-slot-2",
      featureType: "bayonet_receiving_slot",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(135, "photo_scaled", J),
      startAngleDeg: v(118, "photo_scaled", J),
      endAngleDeg: v(152, "photo_scaled", J),
      innerRadiusMm: v(25.8, "photo_scaled", J),
      outerRadiusMm: v(28.8, "photo_scaled", J),
      depthMm: v(2, "photo_scaled", J),
      matesWith: "lens-lug-2",
      shapeNotes: "four-lug bayonet [lm-2]",
    },
    {
      featureId: "body-slot-3",
      featureType: "bayonet_receiving_slot",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(225, "photo_scaled", J),
      startAngleDeg: v(208, "photo_scaled", J),
      endAngleDeg: v(242, "photo_scaled", J),
      innerRadiusMm: v(25.8, "photo_scaled", J),
      outerRadiusMm: v(28.8, "photo_scaled", J),
      depthMm: v(2, "photo_scaled", J),
      matesWith: "lens-lug-3",
      shapeNotes: "four-lug bayonet [lm-2]",
    },
    {
      featureId: "body-slot-4",
      featureType: "bayonet_receiving_slot",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(315, "photo_scaled", J),
      startAngleDeg: v(298, "photo_scaled", J),
      endAngleDeg: v(332, "photo_scaled", J),
      innerRadiusMm: v(25.8, "photo_scaled", J),
      outerRadiusMm: v(28.8, "photo_scaled", J),
      depthMm: v(2, "photo_scaled", J),
      matesWith: "lens-lug-4",
      shapeNotes: "four-lug bayonet [lm-2]",
    },
    {
      featureId: "body-index-mark",
      featureType: "index_mark",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(180, "photo_scaled", J),
      startAngleDeg: unknownV(J),
      endAngleDeg: unknownV(J),
      innerRadiusMm: unknownV(J),
      outerRadiusMm: v(31.5, "photo_scaled", J),
      depthMm: naV(),
      matesWith: "lens-index-mark",
      shapeNotes: "mounting index (offset from the top contact bank)",
    },
    {
      featureId: "body-lock-pin",
      featureType: "lock_pin",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(135, "secondary", J),
      startAngleDeg: unknownV(J),
      endAngleDeg: unknownV(J),
      innerRadiusMm: unknownV(J),
      outerRadiusMm: v(26.5, "photo_scaled", J),
      depthMm: v(2, "photo_scaled", J),
      matesWith: "lens-lock-notch",
      shapeNotes: "locking groove at 4:30 [lm-2]",
    },
  ],

  lensSideFeatures: [
    {
      featureId: "lens-throat",
      featureType: "lens_throat",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(24.8, "photo_scaled", J),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "rear opening",
    },
    {
      featureId: "lens-mount-ring",
      featureType: "lens_mount_ring",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", J),
      startAngleDeg: v(0, "photo_scaled", J),
      endAngleDeg: v(360, "photo_scaled", J),
      innerRadiusMm: v(24.8, "photo_scaled", J),
      outerRadiusMm: v(30, "photo_scaled", J),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "lens flange ring",
    },
    {
      featureId: "lens-lug-1",
      featureType: "bayonet_lug",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(45, "photo_scaled", J),
      startAngleDeg: v(28, "photo_scaled", J),
      endAngleDeg: v(62, "photo_scaled", J),
      innerRadiusMm: v(25.8, "photo_scaled", J),
      outerRadiusMm: v(28.8, "photo_scaled", J),
      thicknessMm: v(2, "photo_scaled", J),
      matesWith: "body-slot-1",
      shapeNotes: "four-lug bayonet [lm-2]",
    },
    {
      featureId: "lens-lug-2",
      featureType: "bayonet_lug",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(135, "photo_scaled", J),
      startAngleDeg: v(118, "photo_scaled", J),
      endAngleDeg: v(152, "photo_scaled", J),
      innerRadiusMm: v(25.8, "photo_scaled", J),
      outerRadiusMm: v(28.8, "photo_scaled", J),
      thicknessMm: v(2, "photo_scaled", J),
      matesWith: "body-slot-2",
      shapeNotes: "four-lug bayonet [lm-2]",
    },
    {
      featureId: "lens-lug-3",
      featureType: "bayonet_lug",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(225, "photo_scaled", J),
      startAngleDeg: v(208, "photo_scaled", J),
      endAngleDeg: v(242, "photo_scaled", J),
      innerRadiusMm: v(25.8, "photo_scaled", J),
      outerRadiusMm: v(28.8, "photo_scaled", J),
      thicknessMm: v(2, "photo_scaled", J),
      matesWith: "body-slot-3",
      shapeNotes: "four-lug bayonet [lm-2]",
    },
    {
      featureId: "lens-lug-4",
      featureType: "bayonet_lug",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(315, "photo_scaled", J),
      startAngleDeg: v(298, "photo_scaled", J),
      endAngleDeg: v(332, "photo_scaled", J),
      innerRadiusMm: v(25.8, "photo_scaled", J),
      outerRadiusMm: v(28.8, "photo_scaled", J),
      thicknessMm: v(2, "photo_scaled", J),
      matesWith: "body-slot-4",
      shapeNotes: "four-lug bayonet [lm-2]",
    },
    {
      featureId: "lens-index-mark",
      featureType: "index_mark",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(180, "photo_scaled", J),
      startAngleDeg: unknownV(J),
      endAngleDeg: unknownV(J),
      innerRadiusMm: unknownV(J),
      outerRadiusMm: v(30.5, "photo_scaled", J),
      thicknessMm: naV(),
      matesWith: "body-index-mark",
      shapeNotes: "aligns with body index",
    },
    {
      featureId: "lens-lock-notch",
      featureType: "lock_notch",
      profileId: "l-mount/base",
      count: 1,
      centerAngleDeg: v(135, "secondary", J),
      startAngleDeg: unknownV(J),
      endAngleDeg: unknownV(J),
      innerRadiusMm: unknownV(J),
      outerRadiusMm: v(26.5, "photo_scaled", J),
      thicknessMm: v(2, "photo_scaled", J),
      matesWith: "body-lock-pin",
      shapeNotes: "receives body lock pin (4:30)",
    },
  ],

  axialStack: [
    {
      planeId: "flange_datum",
      zPositionMm: v(0, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(62, "photo_scaled", J),
    },
    {
      planeId: "bayonet_lug_engagement",
      zPositionMm: v(1, "photo_scaled", J),
      thicknessMm: v(2, "photo_scaled", J),
      diameterMm: v(55, "photo_scaled", J),
    },
    {
      planeId: "electrical_contact_plane",
      zPositionMm: v(0.5, "photo_scaled", J),
      thicknessMm: v(0.5, "photo_scaled", J),
      diameterMm: v(49, "photo_scaled", J),
    },
    {
      planeId: "sensor_film_plane",
      zPositionMm: v(-20, "official", O),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(43.3, "secondary", W),
    },
  ],

  contacts: [
    {
      side: "body",
      contactNo: 1,
      profileId: "l-mount/base",
      centerAngleDeg: v(330, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 2,
      profileId: "l-mount/base",
      centerAngleDeg: v(336, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 3,
      profileId: "l-mount/base",
      centerAngleDeg: v(342, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 4,
      profileId: "l-mount/base",
      centerAngleDeg: v(348, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 5,
      profileId: "l-mount/base",
      centerAngleDeg: v(354, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 6,
      profileId: "l-mount/base",
      centerAngleDeg: v(0, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 7,
      profileId: "l-mount/base",
      centerAngleDeg: v(6, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 8,
      profileId: "l-mount/base",
      centerAngleDeg: v(12, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 9,
      profileId: "l-mount/base",
      centerAngleDeg: v(18, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "body",
      contactNo: 10,
      profileId: "l-mount/base",
      centerAngleDeg: v(24, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.5, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 1,
      profileId: "l-mount/base",
      centerAngleDeg: v(330, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 2,
      profileId: "l-mount/base",
      centerAngleDeg: v(336, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 3,
      profileId: "l-mount/base",
      centerAngleDeg: v(342, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 4,
      profileId: "l-mount/base",
      centerAngleDeg: v(348, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 5,
      profileId: "l-mount/base",
      centerAngleDeg: v(354, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 6,
      profileId: "l-mount/base",
      centerAngleDeg: v(0, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 7,
      profileId: "l-mount/base",
      centerAngleDeg: v(6, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 8,
      profileId: "l-mount/base",
      centerAngleDeg: v(12, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 9,
      profileId: "l-mount/base",
      centerAngleDeg: v(18, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
    {
      side: "lens",
      contactNo: 10,
      profileId: "l-mount/base",
      centerAngleDeg: v(24, "photo_scaled", J),
      centerRadiusMm: v(23.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(3, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "",
    },
  ],

  mechanicalCouplings: [],

  screwsGasketsBaffles: [
    {
      featureId: "body-mount-screws",
      featureType: "mount_screws",
      side: "body",
      count: v(6, "photo_scaled", J),
      pcdMm: v(59, "photo_scaled", J),
      diameterMm: v(2, "photo_scaled", J),
      centerAnglesDeg: degListV([20, 80, 140, 200, 260, 320], "photo_scaled", J),
      shape: "round",
    },
  ],

  svgLayers: {
    mvpRequired: ["datum-axis", "camera-side-metal", "lens-side-metal", "axial-section", "uncertainty"],
    conditionalCoreRequired: ["clear-aperture", "camera-side-core-interface", "lens-side-core-interface"],
    variantRequired: ["camera-side-variant-electrical", "lens-side-variant-electrical"],
  },

  sourceRefs: [
    {
      ref: "lm-official-1",
      sourceType: "official",
      citation: "L-Mount Alliance, “L-Mount | Overview.” Accessed 2026-06-06.",
      liveUrl: "https://l-mount.com/en/Overview",
      archiveUrl: "http://web.archive.org/web/20251116195834/https://l-mount.com/en/Overview",
      archiveDate: "2025-11-16",
      appliesTo: "51.6 mm L-Mount diameter, 20 mm flange distance, and four-tab bayonet",
      confidence: "high",
    },
    {
      ref: "lm-1",
      sourceType: "secondary",
      citation: "“L-Mount,” Wikipedia. Accessed 2026-06-04.",
      liveUrl: "https://en.wikipedia.org/wiki/L-Mount",
      archiveUrl: "http://web.archive.org/web/20251203103305/https://en.wikipedia.org/wiki/L-Mount",
      archiveDate: "2025-12-03",
      appliesTo: "flange focal distance, 51.6 mm throat, ten pins, four lugs, Alliance members",
      confidence: "high",
    },
    {
      ref: "lm-2",
      sourceType: "secondary",
      citation: "“Lens Mounts: L-Mount,” JAPB (japb.net). Accessed 2026-06-04.",
      liveUrl: "https://japb.net/theory/lensmounts/l-mount/",
      archiveUrl: "http://web.archive.org/web/20250618064650/https://japb.net/theory/lensmounts/l-mount/",
      archiveDate: "2025-06-18",
      appliesTo: "locking groove at 4:30, ten contacts across 11–1 o'clock, four-lug bayonet",
      confidence: "medium",
    },
  ],

  openQuestions: [
    {
      issue:
        "Lug angular spans, the mounting-index clock position, and the lock rotation angle/direction are photo-scaled or undocumented; per-contact clock positions are interpolated within the documented 11–1 o'clock (top) band.",
      affectedFields: ["cameraSideFeatures", "lensSideFeatures", "contacts", "lockGeometry"],
      candidateValues: [],
      resolution: "Upgrade to an official L-Mount drawing or measured sample.",
    },
  ],
} satisfies MountSpecInput;

export default L_MOUNT;
