/**
 * Leica M mount SVG specification.
 *
 * Leica's rangefinder bayonet (1954): a very short 27.8 mm flange focal distance, a 44 mm external
 * mount diameter, and a four-lug bayonet. The base profile holds the invariant bayonet plus the
 * rangefinder coupling cam; the `leica-m/6-bit` variant overlays the 6-bit lens-identification coding
 * (a strip of six white/black marks on the lens flange, read optically) found on recent lenses. There
 * are no electrical contacts. The MVP figure renders the 6-bit variant.
 *
 * Sourced scalars: flange focal distance 27.8 mm, 44 mm external diameter, four lugs, rangefinder
 * coupling cam inside the top of the mount, 6-bit coding [leicam-1]; bayonet type and the 6-bit strip
 * also per the JAPB reference [leicam-2]. The throat diameter, the lug/lock/index clock positions, and
 * the cam/coding positions are photo-scaled and flagged in openQuestions.
 */

import type { MountSpecInput } from "../types/mount.js";
import { degListV, dirV, naV, unknownV, v } from "../optics/mount/authoring.js";

const W = ["leicam-1"]; // Wikipedia
const J = ["leicam-2"]; // JAPB teardown

const LEICA_M_MOUNT = {
  mountId: "leica-m",
  displayLabel: "Leica M",
  projectNote: "Leica M bayonet rangefinder mount.",
  researchStatus: "researched",
  mvpStatus: "mvp_complete",
  mechanism: "bayonet",
  lockType: "sprung_detent",

  mvp: {
    requiredViews: ["camera_side_front_view", "lens_side_rear_view", "axial_register_schematic"],
    requirementLevels: {
      mvpRequired: ["flange_focal_distance_mm", "nominal_throat_diameter_mm", "camera_mount_outer_diameter_mm"],
      conditionalCoreRequired: ["bayonet_lugs", "lock_pin", "index_mark", "rangefinder_cam"],
      variantRequired: ["six_bit_coding"],
      mvpOptional: ["mount_screws"],
      referenceGrade: ["lug_ramp_undercut"],
    },
    profileModel: {
      baseProfileId: "leica-m/base",
      selectedMvpProfileId: "leica-m/6-bit",
      variantStrategy: "variant_profiles_defined",
      variantProfiles: [
        {
          profileId: "leica-m/base",
          profileType: "base",
          appliesTo: "all Leica M lenses and bodies, 1954–present",
          adds: ["four bayonet lugs", "lock pin/notch", "mounting index", "rangefinder coupling cam"],
          removes: ["electrical contacts (rangefinder mechanical interface)"],
          changes: [],
          cameraSideOverlayLayers: ["camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-mechanical"],
          status: "researched",
          sourceRefs: W,
        },
        {
          profileId: "leica-m/6-bit",
          profileType: "variant",
          appliesTo: "6-bit-coded M lenses (digital M era)",
          adds: ["6-bit lens-identification coding (six white/black marks on the flange)"],
          removes: [],
          changes: ["camera reads lens identity optically"],
          cameraSideOverlayLayers: ["camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-mechanical"],
          status: "researched",
          sourceRefs: J,
        },
      ],
    },
  },

  coreDimensions: {
    flangeFocalDistanceMm: v(27.8, "secondary", W),
    nominalThroatDiameterMm: v(38.5, "photo_scaled", W),
    effectiveClearApertureMm: v(38.5, "photo_scaled", W),
    cameraMountOuterDiameterMm: v(44, "secondary", W),
    lensMountOuterDiameterMm: v(42, "photo_scaled", W),
    contactCount: naV(),
  },

  lockGeometry: {
    insertionAngleDeg: v(0, "secondary", W),
    lockAngleDeg: unknownV(W),
    lockRotationDeg: unknownV(W),
    lockRotationDirection: dirV("unknown", "unknown", []),
  },

  cameraSideFeatures: [
    {
      featureId: "body-throat",
      featureType: "body_throat",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(19.25, "photo_scaled", W),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "rangefinder mount opening",
    },
    {
      featureId: "body-mount-ring",
      featureType: "mount_ring",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: v(0, "photo_scaled", W),
      endAngleDeg: v(360, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(22, "secondary", W),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "44 mm external diameter",
    },
    {
      featureId: "body-slot-1",
      featureType: "bayonet_receiving_slot",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(45, "photo_scaled", W),
      startAngleDeg: v(28, "photo_scaled", W),
      endAngleDeg: v(62, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      depthMm: v(1.5, "photo_scaled", W),
      matesWith: "lens-lug-1",
      shapeNotes: "four-lug bayonet [leicam-1]",
    },
    {
      featureId: "body-slot-2",
      featureType: "bayonet_receiving_slot",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(135, "photo_scaled", W),
      startAngleDeg: v(118, "photo_scaled", W),
      endAngleDeg: v(152, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      depthMm: v(1.5, "photo_scaled", W),
      matesWith: "lens-lug-2",
      shapeNotes: "four-lug bayonet [leicam-1]",
    },
    {
      featureId: "body-slot-3",
      featureType: "bayonet_receiving_slot",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(225, "photo_scaled", W),
      startAngleDeg: v(208, "photo_scaled", W),
      endAngleDeg: v(242, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      depthMm: v(1.5, "photo_scaled", W),
      matesWith: "lens-lug-3",
      shapeNotes: "four-lug bayonet [leicam-1]",
    },
    {
      featureId: "body-slot-4",
      featureType: "bayonet_receiving_slot",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(315, "photo_scaled", W),
      startAngleDeg: v(298, "photo_scaled", W),
      endAngleDeg: v(332, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      depthMm: v(1.5, "photo_scaled", W),
      matesWith: "lens-lug-4",
      shapeNotes: "four-lug bayonet [leicam-1]",
    },
    {
      featureId: "body-index-mark",
      featureType: "index_mark",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(22.5, "photo_scaled", W),
      depthMm: naV(),
      matesWith: "lens-index-mark",
      shapeNotes: "mounting index",
    },
    {
      featureId: "body-lock-pin",
      featureType: "lock_pin",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(180, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(20.5, "photo_scaled", W),
      depthMm: v(2, "photo_scaled", W),
      matesWith: "lens-lock-notch",
      shapeNotes: "lock pin (position unconfirmed)",
    },
  ],

  lensSideFeatures: [
    {
      featureId: "lens-throat",
      featureType: "lens_throat",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(18.25, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "rear opening",
    },
    {
      featureId: "lens-mount-ring",
      featureType: "lens_mount_ring",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: v(0, "photo_scaled", W),
      endAngleDeg: v(360, "photo_scaled", W),
      innerRadiusMm: v(18.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "lens flange ring",
    },
    {
      featureId: "lens-lug-1",
      featureType: "bayonet_lug",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(45, "photo_scaled", W),
      startAngleDeg: v(28, "photo_scaled", W),
      endAngleDeg: v(62, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      thicknessMm: v(1.5, "photo_scaled", W),
      matesWith: "body-slot-1",
      shapeNotes: "four-lug bayonet [leicam-1]",
    },
    {
      featureId: "lens-lug-2",
      featureType: "bayonet_lug",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(135, "photo_scaled", W),
      startAngleDeg: v(118, "photo_scaled", W),
      endAngleDeg: v(152, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      thicknessMm: v(1.5, "photo_scaled", W),
      matesWith: "body-slot-2",
      shapeNotes: "four-lug bayonet [leicam-1]",
    },
    {
      featureId: "lens-lug-3",
      featureType: "bayonet_lug",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(225, "photo_scaled", W),
      startAngleDeg: v(208, "photo_scaled", W),
      endAngleDeg: v(242, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      thicknessMm: v(1.5, "photo_scaled", W),
      matesWith: "body-slot-3",
      shapeNotes: "four-lug bayonet [leicam-1]",
    },
    {
      featureId: "lens-lug-4",
      featureType: "bayonet_lug",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(315, "photo_scaled", W),
      startAngleDeg: v(298, "photo_scaled", W),
      endAngleDeg: v(332, "photo_scaled", W),
      innerRadiusMm: v(19.25, "photo_scaled", W),
      outerRadiusMm: v(21.5, "photo_scaled", W),
      thicknessMm: v(1.5, "photo_scaled", W),
      matesWith: "body-slot-4",
      shapeNotes: "four-lug bayonet [leicam-1]",
    },
    {
      featureId: "lens-index-mark",
      featureType: "index_mark",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(22, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "body-index-mark",
      shapeNotes: "aligns with body index",
    },
    {
      featureId: "lens-lock-notch",
      featureType: "lock_notch",
      profileId: "leica-m/base",
      count: 1,
      centerAngleDeg: v(180, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(20.5, "photo_scaled", W),
      thicknessMm: v(2, "photo_scaled", W),
      matesWith: "body-lock-pin",
      shapeNotes: "receives body lock pin",
    },
  ],

  axialStack: [
    {
      planeId: "flange_datum",
      zPositionMm: v(0, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(44, "secondary", W),
    },
    {
      planeId: "bayonet_lug_engagement",
      zPositionMm: v(1, "photo_scaled", W),
      thicknessMm: v(1.5, "photo_scaled", W),
      diameterMm: v(40, "photo_scaled", W),
    },
    {
      planeId: "sensor_film_plane",
      zPositionMm: v(-27.8, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(43.3, "secondary", W),
    },
  ],

  contacts: [],

  mechanicalCouplings: [
    {
      featureId: "rangefinder-coupling-cam",
      side: "both",
      profileId: "leica-m/base",
      centerAngleDeg: v(0, "secondary", W),
      radiusMm: v(18, "photo_scaled", W),
      sizeOrTravel: "cam / roller arm",
      function: "couples lens focus to the rangefinder",
      compatibilityNotes: "body roller arm inside the top of the mount",
    },
    {
      featureId: "six-bit-coding",
      side: "lens",
      profileId: "leica-m/6-bit",
      centerAngleDeg: v(200, "photo_scaled", J),
      radiusMm: v(21, "photo_scaled", J),
      sizeOrTravel: "six white/black marks",
      function: "optical lens-identification coding",
      compatibilityNotes: "read by digital M bodies",
    },
  ],

  screwsGasketsBaffles: [
    {
      featureId: "body-mount-screws",
      featureType: "mount_screws",
      side: "body",
      count: v(4, "photo_scaled", W),
      pcdMm: v(41, "photo_scaled", W),
      diameterMm: v(1.6, "photo_scaled", W),
      centerAnglesDeg: degListV([45, 135, 225, 315], "photo_scaled", W),
      shape: "round",
    },
  ],

  svgLayers: {
    mvpRequired: ["datum-axis", "camera-side-metal", "lens-side-metal", "axial-section", "uncertainty"],
    conditionalCoreRequired: ["clear-aperture", "camera-side-core-interface", "lens-side-core-interface"],
    variantRequired: ["camera-side-variant-mechanical", "lens-side-variant-mechanical"],
  },

  sourceRefs: [
    {
      ref: "leicam-1",
      sourceType: "secondary",
      citation: "“Leica M mount,” Wikipedia. Accessed 2026-06-04.",
      liveUrl: "https://en.wikipedia.org/wiki/Leica_M_mount",
      archiveUrl: "http://web.archive.org/web/20221225162235/https://en.wikipedia.org/wiki/Leica_M_mount",
      archiveDate: "2022-12-25",
      appliesTo: "flange focal distance, 44 mm external diameter, four lugs, rangefinder cam, 6-bit coding",
      confidence: "medium",
    },
    {
      ref: "leicam-2",
      sourceType: "secondary",
      citation: "“Lens Mounts: Leica M,” JAPB (japb.net). Accessed 2026-06-04.",
      liveUrl: "https://japb.net/theory/lensmounts/leica-m/",
      archiveUrl: "http://web.archive.org/web/20250429113337/https://japb.net/theory/lensmounts/leica-m/",
      archiveDate: "2025-04-29",
      appliesTo: "bayonet type, focusing-distance coupling, 6-bit coding strip",
      confidence: "medium",
    },
  ],

  openQuestions: [
    {
      issue:
        "Leica M lacks an archived teardown with clock positions: the throat diameter, the lug spans, the rangefinder-cam and 6-bit-coding positions, and the lock/index clock positions are photo-scaled.",
      affectedFields: [
        "nominalThroatDiameterMm",
        "cameraSideFeatures",
        "lensSideFeatures",
        "mechanicalCouplings",
        "lockGeometry",
      ],
      candidateValues: [],
      resolution: "Upgrade to an official Leica M mount drawing or measured sample.",
    },
  ],
} satisfies MountSpecInput;

export default LEICA_M_MOUNT;
