/**
 * Nikon F mount SVG specification.
 *
 * One of the longest-lived mounts: an invariant three-lug bayonet foundation carried a long ladder
 * of metering/AF/aperture interfaces. The base profile holds only invariant geometry; named variant
 * overlays capture each mount-face era — pre-AI metering prong, AI / AI-S meter-coupling ridge and
 * indexing, AF-D screw drive + five CPU contacts, and AF-I/AF-S/AF-P in-lens motors with their CPU
 * contact block. Geometry is never averaged across eras. The MVP figure renders the AI-S variant.
 *
 * G (no aperture ring) and E (electromagnetic diaphragm) are aperture-design variations that ride on
 * the AF-S electrical interface rather than distinct mount-face geometry, so they are not modeled as
 * separate profiles; AF-P (stepping motor) is folded into the AF-I/AF-S in-lens-motor profile.
 *
 * Headline dimensions (flange focal distance 46.5 mm, 44 mm throat, three non-symmetric lugs, lock by
 * counter-clockwise rotation viewed from the camera front) and the variant ladder are sourced from
 * the Nikon F-mount reference [nf-1]; AF lenses carry five CPU contacts ("4+1") at the top of the
 * mount, rising to as many as ten on AF-S. Fine angular geometry (lug spans, index/lock/coupling
 * clock positions, contact pitch) is photo-scaled and flagged in openQuestions. Nikon F is the
 * package Section 4.1 lens-rear mirror reference: its mounting index is stored in the camera-front
 * frame and the mirror gate confirms the transform is the left-right reflection.
 */

import type { MountSpecInput } from "../types/mount.js";
import { degListV, dirV, naV, unknownV, v } from "../optics/mount/authoring.js";

const REF = ["nf-1"];

const NIKON_F_MOUNT = {
  mountId: "nikon-f",
  displayLabel: "Nikon F",
  projectNote: "Nikon F SLR mount.",
  researchStatus: "researched",
  mvpStatus: "mvp_complete",
  mechanism: "bayonet",
  lockType: "sprung_detent",

  mvp: {
    requiredViews: ["camera_side_front_view", "lens_side_rear_view", "axial_register_schematic"],
    requirementLevels: {
      mvpRequired: ["flange_focal_distance_mm", "nominal_throat_diameter_mm", "camera_mount_outer_diameter_mm"],
      conditionalCoreRequired: ["bayonet_lugs", "lock_pin", "index_mark"],
      variantRequired: ["metering_prong", "ai_meter_coupling_ridge", "cpu_contacts", "af_screw_coupler"],
      mvpOptional: ["mount_screws"],
      referenceGrade: ["lug_ramp_undercut", "contact_pitch"],
    },
    profileModel: {
      baseProfileId: "nikon-f/base",
      selectedMvpProfileId: "nikon-f/ai-s",
      variantStrategy: "variant_profiles_defined",
      variantProfiles: [
        {
          profileId: "nikon-f/base",
          profileType: "base",
          appliesTo: "all Nikon F bodies and lenses, 1959–present",
          adds: ["three non-symmetric bayonet lugs", "lock pin/notch", "mounting index"],
          removes: [],
          changes: [],
          sourceRefs: [...REF, "nf-p1", "nf-p2"],
        },
        {
          profileId: "nikon-f/non-ai",
          profileType: "variant",
          appliesTo: "pre-AI ('F') lenses, 1959–1977",
          adds: ["metering coupling prong ('rabbit ears') / coupling shoe"],
          removes: [],
          changes: ["maximum-aperture metering set by the prong/shoe"],
          cameraSideOverlayLayers: ["camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-mechanical"],
          status: "researched",
          sourceRefs: REF,
        },
        {
          profileId: "nikon-f/ai",
          profileType: "variant",
          appliesTo: "AI (Automatic Indexing) lenses, 1977+",
          adds: ["meter coupling ridge", "lens speed indexing post", "aperture direct readout (ADR) prong"],
          removes: [],
          changes: ["maximum-aperture indexing automated vs the pre-AI prong"],
          cameraSideOverlayLayers: ["camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-mechanical"],
          status: "researched",
          sourceRefs: REF,
        },
        {
          profileId: "nikon-f/ai-s",
          profileType: "variant",
          appliesTo: "AI-S lenses, 1981+ (renders the AI/AI-S meter-coupling ridge introduced by AI)",
          adds: ["AI-S lens-type signal notch", "focal-length indexing ridge"],
          removes: [],
          changes: ["linear aperture actuation for shutter-priority / program AE"],
          cameraSideOverlayLayers: ["camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-mechanical"],
          status: "researched",
          sourceRefs: REF,
        },
        {
          profileId: "nikon-f/af-d",
          profileType: "variant",
          appliesTo: "AF / AF-D screw-drive autofocus lenses",
          adds: ["AF screw-drive coupler", "five CPU contacts ('4+1')", "subject-distance (D) encoding"],
          removes: [],
          changes: ["electronic aperture/distance reporting added"],
          cameraSideOverlayLayers: ["camera-side-variant-electrical", "camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-electrical"],
          status: "researched",
          sourceRefs: REF,
        },
        {
          profileId: "nikon-f/af-i-af-s",
          profileType: "variant",
          appliesTo: "AF-I, AF-S and AF-P in-lens-motor lenses (incl. G and E aperture variants)",
          adds: ["in-lens AF motor (AF-I coreless / AF-S SWM / AF-P stepping)", "CPU contact block (up to ten)"],
          removes: [],
          changes: ["body AF screw coupler unused; AF driven in the lens; AF-P incompatible with many older bodies"],
          cameraSideOverlayLayers: ["camera-side-variant-electrical"],
          lensSideOverlayLayers: ["lens-side-variant-electrical"],
          status: "researched",
          sourceRefs: REF,
        },
      ],
    },
  },

  coreDimensions: {
    flangeFocalDistanceMm: v(46.5, "secondary", REF),
    nominalThroatDiameterMm: v(44, "secondary", REF),
    effectiveClearApertureMm: v(44, "secondary", REF),
    cameraMountOuterDiameterMm: v(54, "photo_scaled", REF),
    lensMountOuterDiameterMm: v(50, "photo_scaled", REF),
    contactCount: v(5, "secondary", REF),
  },

  lockGeometry: {
    insertionAngleDeg: v(0, "secondary", REF),
    lockAngleDeg: v(54, "photo_scaled", REF),
    lockRotationDeg: v(54, "photo_scaled", REF),
    lockRotationDirection: dirV("counterclockwise", "secondary", REF),
  },

  cameraSideFeatures: [
    {
      featureId: "body-throat",
      featureType: "body_throat",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", REF),
      startAngleDeg: v(0, "secondary", REF),
      endAngleDeg: v(360, "secondary", REF),
      innerRadiusMm: v(0, "secondary", REF),
      outerRadiusMm: v(22, "secondary", REF),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "44 mm throat opening",
    },
    {
      featureId: "body-mount-ring",
      featureType: "mount_ring",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", REF),
      startAngleDeg: v(0, "photo_scaled", REF),
      endAngleDeg: v(360, "photo_scaled", REF),
      innerRadiusMm: v(22, "secondary", REF),
      outerRadiusMm: v(27, "photo_scaled", REF),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "visible body mount ring",
    },
    {
      featureId: "body-slot-1",
      featureType: "bayonet_receiving_slot",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(60, "photo_scaled", REF),
      startAngleDeg: v(44, "photo_scaled", REF),
      endAngleDeg: v(76, "photo_scaled", REF),
      innerRadiusMm: v(22, "photo_scaled", REF),
      outerRadiusMm: v(24.5, "photo_scaled", REF),
      depthMm: v(1.5, "photo_scaled", REF),
      matesWith: "lens-lug-1",
      shapeNotes: "non-symmetric lug [nf-1]",
    },
    {
      featureId: "body-slot-2",
      featureType: "bayonet_receiving_slot",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(180, "photo_scaled", REF),
      startAngleDeg: v(164, "photo_scaled", REF),
      endAngleDeg: v(196, "photo_scaled", REF),
      innerRadiusMm: v(22, "photo_scaled", REF),
      outerRadiusMm: v(24.5, "photo_scaled", REF),
      depthMm: v(1.5, "photo_scaled", REF),
      matesWith: "lens-lug-2",
      shapeNotes: "non-symmetric lug [nf-1]",
    },
    {
      featureId: "body-slot-3",
      featureType: "bayonet_receiving_slot",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(300, "photo_scaled", REF),
      startAngleDeg: v(284, "photo_scaled", REF),
      endAngleDeg: v(316, "photo_scaled", REF),
      innerRadiusMm: v(22, "photo_scaled", REF),
      outerRadiusMm: v(24.5, "photo_scaled", REF),
      depthMm: v(1.5, "photo_scaled", REF),
      matesWith: "lens-lug-3",
      shapeNotes: "non-symmetric lug [nf-1]",
    },
    {
      featureId: "body-index-mark",
      featureType: "index_mark",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(60, "photo_scaled", REF),
      startAngleDeg: unknownV(REF),
      endAngleDeg: unknownV(REF),
      innerRadiusMm: unknownV(REF),
      outerRadiusMm: v(28, "photo_scaled", REF),
      depthMm: naV(),
      matesWith: "lens-index-mark",
      shapeNotes: "mounting index for alignment",
    },
    {
      featureId: "body-lock-pin",
      featureType: "lock_pin",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(270, "photo_scaled", REF),
      startAngleDeg: unknownV(REF),
      endAngleDeg: unknownV(REF),
      innerRadiusMm: unknownV(REF),
      outerRadiusMm: v(23, "photo_scaled", REF),
      depthMm: v(2, "photo_scaled", REF),
      matesWith: "lens-lock-notch",
      shapeNotes: "spring lock pin (JAPB '3 o'clock' in its 6-at-top convention)",
    },
  ],

  lensSideFeatures: [
    {
      featureId: "lens-throat",
      featureType: "lens_throat",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", REF),
      startAngleDeg: v(0, "secondary", REF),
      endAngleDeg: v(360, "secondary", REF),
      innerRadiusMm: v(0, "secondary", REF),
      outerRadiusMm: v(21, "photo_scaled", REF),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "rear opening",
    },
    {
      featureId: "lens-mount-ring",
      featureType: "lens_mount_ring",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", REF),
      startAngleDeg: v(0, "photo_scaled", REF),
      endAngleDeg: v(360, "photo_scaled", REF),
      innerRadiusMm: v(21, "photo_scaled", REF),
      outerRadiusMm: v(25, "photo_scaled", REF),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "lens flange ring",
    },
    {
      featureId: "lens-lug-1",
      featureType: "bayonet_lug",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(60, "photo_scaled", REF),
      startAngleDeg: v(44, "photo_scaled", REF),
      endAngleDeg: v(76, "photo_scaled", REF),
      innerRadiusMm: v(22, "photo_scaled", REF),
      outerRadiusMm: v(24.5, "photo_scaled", REF),
      thicknessMm: v(1.5, "photo_scaled", REF),
      matesWith: "body-slot-1",
      shapeNotes: "non-symmetric lug [nf-1]",
    },
    {
      featureId: "lens-lug-2",
      featureType: "bayonet_lug",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(180, "photo_scaled", REF),
      startAngleDeg: v(164, "photo_scaled", REF),
      endAngleDeg: v(196, "photo_scaled", REF),
      innerRadiusMm: v(22, "photo_scaled", REF),
      outerRadiusMm: v(24.5, "photo_scaled", REF),
      thicknessMm: v(1.5, "photo_scaled", REF),
      matesWith: "body-slot-2",
      shapeNotes: "non-symmetric lug [nf-1]",
    },
    {
      featureId: "lens-lug-3",
      featureType: "bayonet_lug",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(300, "photo_scaled", REF),
      startAngleDeg: v(284, "photo_scaled", REF),
      endAngleDeg: v(316, "photo_scaled", REF),
      innerRadiusMm: v(22, "photo_scaled", REF),
      outerRadiusMm: v(24.5, "photo_scaled", REF),
      thicknessMm: v(1.5, "photo_scaled", REF),
      matesWith: "body-slot-3",
      shapeNotes: "non-symmetric lug [nf-1]",
    },
    {
      featureId: "lens-index-mark",
      featureType: "index_mark",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(60, "photo_scaled", REF),
      startAngleDeg: unknownV(REF),
      endAngleDeg: unknownV(REF),
      innerRadiusMm: unknownV(REF),
      outerRadiusMm: v(26, "photo_scaled", REF),
      thicknessMm: naV(),
      matesWith: "body-index-mark",
      shapeNotes: "aligns with body index (white dot)",
    },
    {
      featureId: "lens-lock-notch",
      featureType: "lock_notch",
      profileId: "nikon-f/base",
      count: 1,
      centerAngleDeg: v(270, "photo_scaled", REF),
      startAngleDeg: unknownV(REF),
      endAngleDeg: unknownV(REF),
      innerRadiusMm: unknownV(REF),
      outerRadiusMm: v(23, "photo_scaled", REF),
      thicknessMm: v(2, "photo_scaled", REF),
      matesWith: "body-lock-pin",
      shapeNotes: "receives body lock pin",
    },
  ],

  axialStack: [
    {
      planeId: "flange_datum",
      zPositionMm: v(0, "secondary", REF),
      thicknessMm: v(0, "secondary", REF),
      diameterMm: v(54, "photo_scaled", REF),
    },
    {
      planeId: "bayonet_lug_engagement",
      zPositionMm: v(1.2, "photo_scaled", REF),
      thicknessMm: v(1.5, "photo_scaled", REF),
      diameterMm: v(49, "photo_scaled", REF),
    },
    {
      planeId: "sensor_film_plane",
      zPositionMm: v(-46.5, "secondary", REF),
      thicknessMm: v(0, "secondary", REF),
      diameterMm: v(43.3, "secondary", REF),
    },
  ],

  contacts: [
    {
      side: "body",
      contactNo: 1,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(348, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "VCC (power)",
    },
    {
      side: "body",
      contactNo: 2,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(354, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "RW1 (tach)",
    },
    {
      side: "body",
      contactNo: 3,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(0, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "SCK (clock)",
    },
    {
      side: "body",
      contactNo: 4,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(6, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "SIO (data)",
    },
    {
      side: "body",
      contactNo: 5,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(12, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "LGND (ground)",
    },
    {
      side: "lens",
      contactNo: 1,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(348, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "VCC (power)",
    },
    {
      side: "lens",
      contactNo: 2,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(354, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "RW1 (tach)",
    },
    {
      side: "lens",
      contactNo: 3,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(0, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "SCK (clock)",
    },
    {
      side: "lens",
      contactNo: 4,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(6, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "SIO (data)",
    },
    {
      side: "lens",
      contactNo: 5,
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(12, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.4, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "LGND (ground)",
    },
    {
      side: "body",
      contactNo: 1,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(340, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "VCC (power)",
    },
    {
      side: "body",
      contactNo: 2,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(346, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "RW / H-S",
    },
    {
      side: "body",
      contactNo: 3,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(352, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "LCLK (clock)",
    },
    {
      side: "body",
      contactNo: 4,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(358, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "LIO (data)",
    },
    {
      side: "body",
      contactNo: 5,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(4, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "RW2 (teleconverter)",
    },
    {
      side: "body",
      contactNo: 6,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(10, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "LBAT (AF-S)",
    },
    {
      side: "body",
      contactNo: 7,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(16, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "PGND (ground)",
    },
    {
      side: "body",
      contactNo: 8,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(22, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", REF),
      function: "PGND (AF-S)",
    },
    {
      side: "lens",
      contactNo: 1,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(340, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "VCC (power)",
    },
    {
      side: "lens",
      contactNo: 2,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(346, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "RW / H-S",
    },
    {
      side: "lens",
      contactNo: 3,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(352, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "LCLK (clock)",
    },
    {
      side: "lens",
      contactNo: 4,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(358, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "LIO (data)",
    },
    {
      side: "lens",
      contactNo: 5,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(4, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "RW2 (teleconverter)",
    },
    {
      side: "lens",
      contactNo: 6,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(10, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "LBAT (AF-S)",
    },
    {
      side: "lens",
      contactNo: 7,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(16, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "PGND (ground)",
    },
    {
      side: "lens",
      contactNo: 8,
      profileId: "nikon-f/af-i-af-s",
      centerAngleDeg: v(22, "photo_scaled", REF),
      centerRadiusMm: v(20, "photo_scaled", REF),
      widthMm: v(1.3, "photo_scaled", REF),
      heightMm: v(2.5, "photo_scaled", REF),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", REF),
      function: "PGND (AF-S)",
    },
  ],

  mechanicalCouplings: [
    {
      featureId: "metering-prong",
      side: "both",
      profileId: "nikon-f/non-ai",
      centerAngleDeg: v(30, "photo_scaled", REF),
      radiusMm: v(27, "photo_scaled", REF),
      sizeOrTravel: "prong ('rabbit ears') on aperture ring",
      function: "pre-AI maximum-aperture metering coupling",
      compatibilityNotes: "couples to the body metering pin/shoe",
    },
    {
      featureId: "ai-meter-coupling-ridge",
      side: "both",
      profileId: "nikon-f/ai-s",
      centerAngleDeg: v(25, "photo_scaled", REF),
      radiusMm: v(26, "photo_scaled", REF),
      sizeOrTravel: "ridge on aperture ring",
      function: "open-aperture metering coupling (AI/AI-S)",
      compatibilityNotes: "AI follower on body",
    },
    {
      featureId: "lens-speed-indexing-post",
      side: "body",
      profileId: "nikon-f/ai-s",
      centerAngleDeg: v(35, "photo_scaled", REF),
      radiusMm: v(24, "photo_scaled", REF),
      sizeOrTravel: "post on mounting flange",
      function: "maximum-aperture indexing",
      compatibilityNotes: "",
    },
    {
      featureId: "af-screw-coupler",
      side: "body",
      profileId: "nikon-f/af-d",
      centerAngleDeg: v(250, "photo_scaled", REF),
      radiusMm: v(19, "photo_scaled", REF),
      sizeOrTravel: "screwdriver blade",
      function: "mechanical AF drive",
      compatibilityNotes: "body-driven AF (AF/AF-D) lenses",
    },
  ],

  screwsGasketsBaffles: [
    {
      featureId: "body-mount-screws",
      featureType: "mount_screws",
      side: "body",
      count: v(5, "photo_scaled", REF),
      pcdMm: v(50, "photo_scaled", REF),
      diameterMm: v(2, "photo_scaled", REF),
      centerAnglesDeg: degListV([30, 102, 174, 246, 318], "photo_scaled", REF),
      shape: "round",
    },
  ],

  svgLayers: {
    mvpRequired: ["datum-axis", "camera-side-metal", "lens-side-metal", "axial-section", "uncertainty"],
    conditionalCoreRequired: ["clear-aperture", "camera-side-core-interface", "lens-side-core-interface"],
    variantRequired: [
      "camera-side-variant-electrical",
      "camera-side-variant-mechanical",
      "lens-side-variant-electrical",
      "lens-side-variant-mechanical",
    ],
  },

  sourceRefs: [
    {
      ref: "nf-1",
      sourceType: "secondary",
      citation: "“Nikon F-mount,” Wikipedia. Accessed 2026-06-04.",
      liveUrl: "https://en.wikipedia.org/wiki/Nikon_F-mount",
      archiveUrl: "http://web.archive.org/web/20260513020722/https://en.wikipedia.org/wiki/Nikon_F-mount",
      archiveDate: "2026-05-13",
      appliesTo:
        "flange focal distance, throat, three non-symmetric lugs, CCW lock, AI/AI-S/AF/AF-S ladder, CPU contacts",
      confidence: "high",
    },
    {
      ref: "nf-p1",
      sourceType: "patent",
      citation: "US4766453A, Nikon AF-era F-mount bayonet/drive/contact arrangement. Accessed 2026-06-06.",
      liveUrl: "https://patents.google.com/patent/US4766453A/en",
      archiveUrl: "https://patents.google.com/patent/US4766453A/en",
      archiveDate: "2026-06-06",
      appliesTo: "AF-era Nikon F mount bayonet/drive/contact research lead",
      confidence: "low",
    },
    {
      ref: "nf-p2",
      sourceType: "patent",
      citation: "US5185622A, Nikon AF-era F-mount/contact arrangement. Accessed 2026-06-06.",
      liveUrl: "https://patents.google.com/patent/US5185622A/en",
      archiveUrl: "https://patents.google.com/patent/US5185622A/en",
      archiveDate: "2026-06-06",
      appliesTo: "AF-era Nikon F mount/contact research lead",
      confidence: "low",
    },
  ],

  openQuestions: [
    {
      issue:
        "Exact bayonet lug/slot angular spans and the mounting-index/lock-pin clock positions are photo-scaled; the JAPB teardown uses a 6-o'clock-at-top convention, so its clock positions are not adopted directly.",
      affectedFields: ["cameraSideFeatures", "lensSideFeatures", "body-index-mark", "body-lock-pin"],
      candidateValues: [],
      resolution: "Upgrade to an official Nikon mount drawing or measured sample.",
    },
    {
      issue:
        "AF-D carries five CPU contacts ('4+1'); AF-I/AF-S/AF-P carry up to ten. The five AF-D and eight AF-I/AF-S contacts modeled here are representative sets; functions are service-manual labels carried as descriptive text.",
      affectedFields: ["contacts", "contactCount"],
      candidateValues: [5, 7, 8, 10],
      resolution: "Model per-variant contact maps from an official Nikon service reference.",
    },
  ],
} satisfies MountSpecInput;

export default NIKON_F_MOUNT;
