/**
 * Pentax K mount SVG specification.
 *
 * The original K bayonet foundation persisted while the electronic/AF/power/diaphragm interface
 * evolved, so the base profile holds only invariant geometry and named variants overlay each era:
 * `pentax-k/k` (original mechanical aperture coupling), `pentax-k/ka` (six information contacts),
 * `pentax-k/kaf` (AF screw-drive coupler + seventh contact), `pentax-k/kaf2` (two power contacts),
 * `pentax-k/kaf3` (body AF coupler removed; in-lens SDM/DC motor) and `pentax-k/kaf4` (electromagnetic
 * diaphragm; aperture lever removed). Geometry is never averaged across eras. The MVP figure renders
 * the KA era (which retains the original mechanical levers).
 *
 * Sourced layout: flange focal distance 45.46 mm, lock by an approx. 70° clockwise turn [pk-1]; a
 * three-pronged bayonet (two straight edges), a locking groove at roughly 3:45, and six KA contacts
 * (m1, m2, r1, r2, r3, plus the recessed A-position contact) per the JAPB teardown [pk-2].
 * US4017878A directly documents the Asahi bayonet body washer, internal claws, lens/adapter external
 * claws, lock pin/groove, bayonet spring, stopper, and clockwise bayonet engagement [pk-p1].
 * US4357089A documents the Asahi/Pentax opposed mount-surface contact arrangement used for diaphragm
 * value and AUTO/MANUAL information [pk-p2]. US4939532A documents the later AF joint shaft plus
 * retractable power/data contacts coordinated with the mount lock [pk-p3]. Exact K production lug
 * spans and per-contact clock positions remain normalized to JAPB/body imagery and are flagged in
 * openQuestions.
 */

import type { MountSpecInput } from "../types/mount.js";
import { degListV, dirV, naV, unknownV, v } from "../optics/mount/authoring.js";

const W = ["pk-1"]; // Wikipedia
const J = ["pk-2"]; // JAPB teardown
const P1 = ["pk-p1"]; // Asahi K bayonet/adapter patent
const P1J = ["pk-p1", "pk-2"];
const P2J = ["pk-p2", "pk-2"]; // Asahi/Pentax KA contact arrangement patent + production clocking
const P3J = ["pk-p3", "pk-2"]; // Asahi/Pentax AF joint shaft patent + production clocking
const P3W = ["pk-p3", "pk-1"]; // Asahi/Pentax power-contact patent + KAF2 lineage

const PENTAX_K_MOUNT = {
  mountId: "pentax-k",
  displayLabel: "Pentax K",
  projectNote: "Pentax K mount family.",
  researchStatus: "researched",
  mvpStatus: "mvp_complete",
  mechanism: "bayonet",
  lockType: "sprung_detent",

  mvp: {
    requiredViews: ["camera_side_front_view", "lens_side_rear_view", "axial_register_schematic"],
    requirementLevels: {
      mvpRequired: ["flange_focal_distance_mm", "nominal_throat_diameter_mm", "camera_mount_outer_diameter_mm"],
      conditionalCoreRequired: ["bayonet_lugs", "lock_pin", "index_mark"],
      variantRequired: ["aperture_coupling", "ka_contacts", "af_screw_coupler", "power_contacts"],
      mvpOptional: ["mount_screws"],
      referenceGrade: ["lug_ramp_undercut", "contact_pitch"],
    },
    profileModel: {
      baseProfileId: "pentax-k/base",
      selectedMvpProfileId: "pentax-k/ka",
      variantStrategy: "variant_profiles_defined",
      variantProfiles: [
        {
          profileId: "pentax-k/base",
          profileType: "base",
          appliesTo: "all Pentax K bodies and lenses, 1975–present",
          adds: ["three-lug bayonet (two straight edges)", "lock pin/notch", "mounting index"],
          removes: [],
          changes: [],
          sourceRefs: [...W, "pk-p1"],
        },
        {
          profileId: "pentax-k/k",
          profileType: "variant",
          appliesTo: "original K (M-series era) lenses, 1975+",
          adds: ["aperture stop-down coupler", "diaphragm release lever"],
          removes: [],
          changes: ["mechanical aperture interface; KA retains these levers (rendered under the KA figure)"],
          cameraSideOverlayLayers: ["camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-mechanical"],
          status: "researched",
          sourceRefs: [...J, "pk-p2"],
        },
        {
          profileId: "pentax-k/ka",
          profileType: "variant",
          appliesTo: "KA (A-series) bodies and lenses, 1983+",
          adds: ["six A-position information contacts (m1, m2, r1, r2, r3, *)"],
          removes: [],
          changes: ["aperture automation via the contacts; retains the original mechanical levers"],
          cameraSideOverlayLayers: ["camera-side-variant-electrical", "camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-electrical"],
          status: "researched",
          sourceRefs: [...J, "pk-p2"],
        },
        {
          profileId: "pentax-k/kaf",
          profileType: "variant",
          appliesTo: "KAF autofocus bodies and lenses",
          adds: ["AF screw-drive coupler", "seventh digital information contact"],
          removes: [],
          changes: [],
          cameraSideOverlayLayers: ["camera-side-variant-electrical", "camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-electrical", "lens-side-variant-mechanical"],
          status: "researched",
          sourceRefs: [...J, "pk-p3"],
        },
        {
          profileId: "pentax-k/kaf2",
          profileType: "variant",
          appliesTo: "KAF2 power-zoom bodies and lenses",
          adds: ["two power contacts inside the mounting ring"],
          removes: [],
          changes: [],
          cameraSideOverlayLayers: ["camera-side-variant-electrical", "camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-electrical", "lens-side-variant-mechanical"],
          status: "researched",
          sourceRefs: [...W, "pk-p3"],
        },
        {
          profileId: "pentax-k/kaf3",
          profileType: "variant",
          appliesTo: "KAF3 lenses (SDM/DC in-lens motor)",
          adds: [],
          removes: ["body AF screw-drive coupler"],
          changes: ["autofocus driven in the lens"],
          status: "researched",
          sourceRefs: W,
        },
        {
          profileId: "pentax-k/kaf4",
          profileType: "variant",
          appliesTo: "KAF4 lenses (electromagnetic diaphragm)",
          adds: ["electromagnetic diaphragm control"],
          removes: ["mechanical aperture (diaphragm) lever"],
          changes: ["aperture actuated electronically"],
          status: "researched",
          sourceRefs: W,
        },
      ],
    },
  },

  coreDimensions: {
    flangeFocalDistanceMm: v(45.46, "secondary", W),
    nominalThroatDiameterMm: v(44, "secondary", W),
    effectiveClearApertureMm: v(44, "secondary", W),
    cameraMountOuterDiameterMm: v(56, "photo_scaled", J),
    lensMountOuterDiameterMm: v(52, "photo_scaled", J),
    contactCount: v(6, "patent", P2J),
  },

  lockGeometry: {
    insertionAngleDeg: v(0, "secondary", W),
    lockAngleDeg: v(70, "secondary", W),
    lockRotationDeg: v(70, "secondary", W),
    lockRotationDirection: dirV("clockwise", "patent", P1),
  },

  cameraSideFeatures: [
    {
      featureId: "body-throat",
      featureType: "body_throat",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(22, "secondary", W),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "~44 mm throat opening",
    },
    {
      featureId: "body-mount-ring",
      featureType: "mount_ring",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", J),
      startAngleDeg: v(0, "photo_scaled", J),
      endAngleDeg: v(360, "photo_scaled", J),
      innerRadiusMm: v(22, "secondary", W),
      outerRadiusMm: v(28, "photo_scaled", J),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "visible body mount ring",
    },
    {
      featureId: "body-slot-1",
      featureType: "bayonet_receiving_slot",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(30, "patent", P1J),
      startAngleDeg: v(12, "patent", P1J),
      endAngleDeg: v(48, "patent", P1J),
      innerRadiusMm: v(22, "patent", P1J),
      outerRadiusMm: v(24.5, "patent", P1J),
      depthMm: v(1.6, "patent", P1),
      matesWith: "lens-lug-1",
      shapeNotes: "three-claw body bayonet washer from US4017878A, normalized to JAPB/Pentax K clocking",
    },
    {
      featureId: "body-slot-2",
      featureType: "bayonet_receiving_slot",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(150, "patent", P1J),
      startAngleDeg: v(132, "patent", P1J),
      endAngleDeg: v(168, "patent", P1J),
      innerRadiusMm: v(22, "patent", P1J),
      outerRadiusMm: v(24.5, "patent", P1J),
      depthMm: v(1.6, "patent", P1),
      matesWith: "lens-lug-2",
      shapeNotes: "three-claw body bayonet washer from US4017878A, normalized to JAPB/Pentax K clocking",
    },
    {
      featureId: "body-slot-3",
      featureType: "bayonet_receiving_slot",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(270, "patent", P1J),
      startAngleDeg: v(252, "patent", P1J),
      endAngleDeg: v(288, "patent", P1J),
      innerRadiusMm: v(22, "patent", P1J),
      outerRadiusMm: v(24.5, "patent", P1J),
      depthMm: v(1.6, "patent", P1),
      matesWith: "lens-lug-3",
      shapeNotes: "three-claw body bayonet washer from US4017878A, normalized to JAPB/Pentax K clocking",
    },
    {
      featureId: "body-index-mark",
      featureType: "index_mark",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", J),
      startAngleDeg: unknownV(J),
      endAngleDeg: unknownV(J),
      innerRadiusMm: unknownV(J),
      outerRadiusMm: v(29, "photo_scaled", J),
      depthMm: naV(),
      matesWith: "lens-index-mark",
      shapeNotes: "mounting index",
    },
    {
      featureId: "body-lock-pin",
      featureType: "lock_pin",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(112.5, "patent", P1J),
      startAngleDeg: v(112.5, "patent", P1J),
      endAngleDeg: v(112.5, "patent", P1J),
      innerRadiusMm: v(23, "patent", P1J),
      outerRadiusMm: v(23, "patent", P1J),
      depthMm: v(2, "patent", P1),
      matesWith: "lens-lock-notch",
      shapeNotes: "body lock pin 16 engaging the lens/adapter-side lock groove in US4017878A",
    },
  ],

  lensSideFeatures: [
    {
      featureId: "lens-throat",
      featureType: "lens_throat",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(21, "photo_scaled", J),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "rear opening",
    },
    {
      featureId: "lens-mount-ring",
      featureType: "lens_mount_ring",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", J),
      startAngleDeg: v(0, "photo_scaled", J),
      endAngleDeg: v(360, "photo_scaled", J),
      innerRadiusMm: v(21, "photo_scaled", J),
      outerRadiusMm: v(26, "photo_scaled", J),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "lens flange ring",
    },
    {
      featureId: "lens-lug-1",
      featureType: "bayonet_lug",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(30, "patent", P1J),
      startAngleDeg: v(12, "patent", P1J),
      endAngleDeg: v(48, "patent", P1J),
      innerRadiusMm: v(22, "patent", P1J),
      outerRadiusMm: v(24.5, "patent", P1J),
      thicknessMm: v(1.6, "patent", P1),
      matesWith: "body-slot-1",
      shapeNotes: "external bayonet claw/barrel 18/19 from US4017878A, normalized to JAPB/Pentax K clocking",
    },
    {
      featureId: "lens-lug-2",
      featureType: "bayonet_lug",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(150, "patent", P1J),
      startAngleDeg: v(132, "patent", P1J),
      endAngleDeg: v(168, "patent", P1J),
      innerRadiusMm: v(22, "patent", P1J),
      outerRadiusMm: v(24.5, "patent", P1J),
      thicknessMm: v(1.6, "patent", P1),
      matesWith: "body-slot-2",
      shapeNotes: "external bayonet claw/barrel 18/19 from US4017878A, normalized to JAPB/Pentax K clocking",
    },
    {
      featureId: "lens-lug-3",
      featureType: "bayonet_lug",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(270, "patent", P1J),
      startAngleDeg: v(252, "patent", P1J),
      endAngleDeg: v(288, "patent", P1J),
      innerRadiusMm: v(22, "patent", P1J),
      outerRadiusMm: v(24.5, "patent", P1J),
      thicknessMm: v(1.6, "patent", P1),
      matesWith: "body-slot-3",
      shapeNotes: "external bayonet claw/barrel 18/19 from US4017878A, normalized to JAPB/Pentax K clocking",
    },
    {
      featureId: "lens-index-mark",
      featureType: "index_mark",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", J),
      startAngleDeg: unknownV(J),
      endAngleDeg: unknownV(J),
      innerRadiusMm: unknownV(J),
      outerRadiusMm: v(27, "photo_scaled", J),
      thicknessMm: naV(),
      matesWith: "body-index-mark",
      shapeNotes: "aligns with body index",
    },
    {
      featureId: "lens-lock-notch",
      featureType: "lock_notch",
      profileId: "pentax-k/base",
      count: 1,
      centerAngleDeg: v(112.5, "patent", P1J),
      startAngleDeg: v(112.5, "patent", P1J),
      endAngleDeg: v(112.5, "patent", P1J),
      innerRadiusMm: v(23, "patent", P1J),
      outerRadiusMm: v(23, "patent", P1J),
      thicknessMm: v(2, "patent", P1),
      matesWith: "body-lock-pin",
      shapeNotes: "lock groove/recess 18' receiving body lock pin 16 in US4017878A",
    },
  ],

  axialStack: [
    {
      planeId: "flange_datum",
      zPositionMm: v(0, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(56, "photo_scaled", J),
    },
    {
      planeId: "bayonet_lug_engagement",
      zPositionMm: v(1.2, "photo_scaled", J),
      thicknessMm: v(1.6, "photo_scaled", J),
      diameterMm: v(49, "photo_scaled", J),
    },
    {
      planeId: "sensor_film_plane",
      zPositionMm: v(-45.46, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(43.3, "secondary", W),
    },
  ],

  contacts: [
    {
      side: "body",
      contactNo: 1,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(215, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0.4, "patent", P2J),
      function: "* (A-position, recessed)",
    },
    {
      side: "body",
      contactNo: 2,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(223, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0.4, "patent", P2J),
      function: "m1",
    },
    {
      side: "body",
      contactNo: 3,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(231, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0.4, "patent", P2J),
      function: "m2",
    },
    {
      side: "body",
      contactNo: 4,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(239, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0.4, "patent", P2J),
      function: "r1",
    },
    {
      side: "body",
      contactNo: 5,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(247, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0.4, "patent", P2J),
      function: "r2",
    },
    {
      side: "body",
      contactNo: 6,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(255, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0.4, "patent", P2J),
      function: "r3",
    },
    {
      side: "lens",
      contactNo: 1,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(215, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0, "patent", P2J),
      function: "* (A-position, recessed)",
    },
    {
      side: "lens",
      contactNo: 2,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(223, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0, "patent", P2J),
      function: "m1",
    },
    {
      side: "lens",
      contactNo: 3,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(231, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0, "patent", P2J),
      function: "m2",
    },
    {
      side: "lens",
      contactNo: 4,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(239, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0, "patent", P2J),
      function: "r1",
    },
    {
      side: "lens",
      contactNo: 5,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(247, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0, "patent", P2J),
      function: "r2",
    },
    {
      side: "lens",
      contactNo: 6,
      profileId: "pentax-k/ka",
      centerAngleDeg: v(255, "patent", P2J),
      centerRadiusMm: v(20.5, "patent", P2J),
      widthMm: v(1.3, "patent", P2J),
      heightMm: v(2.4, "patent", P2J),
      shape: "pad",
      protrusionMm: v(0, "patent", P2J),
      function: "r3",
    },
    {
      side: "body",
      contactNo: 7,
      profileId: "pentax-k/kaf",
      centerAngleDeg: v(263, "photo_scaled", J),
      centerRadiusMm: v(20.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(2.4, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", J),
      function: "digital info (KAF)",
    },
    {
      side: "lens",
      contactNo: 7,
      profileId: "pentax-k/kaf",
      centerAngleDeg: v(263, "photo_scaled", J),
      centerRadiusMm: v(20.5, "photo_scaled", J),
      widthMm: v(1.3, "photo_scaled", J),
      heightMm: v(2.4, "photo_scaled", J),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", J),
      function: "digital info (KAF)",
    },
    {
      side: "body",
      contactNo: 8,
      profileId: "pentax-k/kaf2",
      centerAngleDeg: v(200, "patent", P3W),
      centerRadiusMm: v(23.5, "patent", P3W),
      widthMm: v(1.6, "patent", P3W),
      heightMm: v(2.4, "patent", P3W),
      shape: "pad",
      protrusionMm: v(0.4, "patent", P3W),
      function: "power (KAF2)",
    },
    {
      side: "body",
      contactNo: 9,
      profileId: "pentax-k/kaf2",
      centerAngleDeg: v(270, "patent", P3W),
      centerRadiusMm: v(23.5, "patent", P3W),
      widthMm: v(1.6, "patent", P3W),
      heightMm: v(2.4, "patent", P3W),
      shape: "pad",
      protrusionMm: v(0.4, "patent", P3W),
      function: "power (KAF2)",
    },
    {
      side: "lens",
      contactNo: 8,
      profileId: "pentax-k/kaf2",
      centerAngleDeg: v(200, "patent", P3W),
      centerRadiusMm: v(23.5, "patent", P3W),
      widthMm: v(1.6, "patent", P3W),
      heightMm: v(2.4, "patent", P3W),
      shape: "pad",
      protrusionMm: v(0, "patent", P3W),
      function: "power/data mating contact (KAF2)",
    },
    {
      side: "lens",
      contactNo: 9,
      profileId: "pentax-k/kaf2",
      centerAngleDeg: v(270, "patent", P3W),
      centerRadiusMm: v(23.5, "patent", P3W),
      widthMm: v(1.6, "patent", P3W),
      heightMm: v(2.4, "patent", P3W),
      shape: "pad",
      protrusionMm: v(0, "patent", P3W),
      function: "power/data mating contact (KAF2)",
    },
  ],

  mechanicalCouplings: [
    {
      featureId: "aperture-stop-down-coupler",
      side: "body",
      profileId: "pentax-k/ka",
      centerAngleDeg: v(300, "photo_scaled", J),
      radiusMm: v(24, "photo_scaled", J),
      sizeOrTravel: "lever",
      function: "sense aperture-ring setting",
      compatibilityNotes: "original K mechanical interface, retained through KAF3",
    },
    {
      featureId: "diaphragm-release-lever",
      side: "body",
      profileId: "pentax-k/ka",
      centerAngleDeg: v(285, "photo_scaled", J),
      radiusMm: v(23, "photo_scaled", J),
      sizeOrTravel: "lever",
      function: "hold open spring-loaded diaphragm",
      compatibilityNotes: "removed on KAF4 (electromagnetic diaphragm)",
    },
    {
      featureId: "af-screw-coupler",
      side: "body",
      profileId: "pentax-k/kaf",
      centerAngleDeg: v(250, "patent", P3J),
      radiusMm: v(18, "patent", P3J),
      sizeOrTravel: "drive shaft",
      function: "mechanical AF drive",
      compatibilityNotes: "removed on KAF3 (in-lens SDM/DC motor)",
    },
    {
      featureId: "af-driven-shaft",
      side: "lens",
      profileId: "pentax-k/kaf",
      centerAngleDeg: v(250, "patent", P3J),
      radiusMm: v(18, "patent", P3J),
      sizeOrTravel: "driven shaft receiver",
      function: "mechanical AF drive receiver",
      compatibilityNotes: "mates with the body AF joint shaft in KAF/KAF2 screw-drive operation",
    },
    {
      featureId: "af-screw-coupler-kaf2",
      side: "body",
      profileId: "pentax-k/kaf2",
      centerAngleDeg: v(250, "patent", P3J),
      radiusMm: v(18, "patent", P3J),
      sizeOrTravel: "drive shaft",
      function: "mechanical AF drive",
      compatibilityNotes: "KAF2 retains screw-drive coupling alongside the power contacts",
    },
    {
      featureId: "af-driven-shaft-kaf2",
      side: "lens",
      profileId: "pentax-k/kaf2",
      centerAngleDeg: v(250, "patent", P3J),
      radiusMm: v(18, "patent", P3J),
      sizeOrTravel: "driven shaft receiver",
      function: "mechanical AF drive receiver",
      compatibilityNotes: "mates with the body AF joint shaft in KAF2 screw-drive operation",
    },
  ],

  screwsGasketsBaffles: [
    {
      featureId: "body-mount-screws",
      featureType: "mount_screws",
      side: "body",
      count: v(4, "photo_scaled", J),
      pcdMm: v(50, "photo_scaled", J),
      diameterMm: v(2, "photo_scaled", J),
      centerAnglesDeg: degListV([45, 135, 225, 315], "photo_scaled", J),
      shape: "round",
    },
  ],

  svgLayers: {
    mvpRequired: ["datum-axis", "camera-side-metal", "lens-side-metal", "axial-section", "uncertainty"],
    conditionalCoreRequired: ["clear-aperture", "camera-side-core-interface", "lens-side-core-interface"],
    variantRequired: [
      "camera-side-variant-electrical",
      "camera-side-variant-mechanical",
      "lens-side-variant-electrical",
      "lens-side-variant-mechanical",
    ],
  },

  sourceRefs: [
    {
      ref: "pk-1",
      sourceType: "secondary",
      citation: "“Pentax K-mount,” Wikipedia. Accessed 2026-06-04.",
      liveUrl: "https://en.wikipedia.org/wiki/Pentax_K-mount",
      archiveUrl: "http://web.archive.org/web/20260512111817/https://en.wikipedia.org/wiki/Pentax_K-mount",
      archiveDate: "2026-05-12",
      appliesTo: "flange focal distance, 70° clockwise lock, KA/KAF/KAF2/KAF3/KAF4 interface evolution",
      confidence: "high",
    },
    {
      ref: "pk-2",
      sourceType: "secondary",
      citation: "“Lens Mounts: Pentax K,” JAPB (japb.net). Accessed 2026-06-04.",
      liveUrl: "https://japb.net/theory/lensmounts/pentax-k/",
      archiveUrl: "http://web.archive.org/web/20260113064419/https://japb.net/theory/lensmounts/pentax-k/",
      archiveDate: "2026-01-13",
      appliesTo:
        "three-prong bayonet (two straight edges), locking groove at ~3:45, six KA contacts (m1/m2/r1/r2/r3/*)",
      confidence: "medium",
    },
    {
      ref: "pk-p1",
      sourceType: "patent",
      citation: 'US4017878A, "Bayonet mount adapter for a camera." Accessed 2026-06-06.',
      liveUrl: "https://patents.google.com/patent/US4017878A/en",
      archiveUrl: "https://patents.google.com/patent/US4017878A/en",
      archiveDate: "2026-06-06",
      appliesTo:
        "Asahi/Pentax bayonet body washer, internal claws, external lens/adapter claws, lock pin/groove, bayonet spring, rotation stopper, and clockwise engagement",
      confidence: "high",
    },
    {
      ref: "pk-p2",
      sourceType: "patent",
      citation:
        'US4357089A, "Electrical contact arrangement for photographic camera with interchangeable lens." Accessed 2026-06-06.',
      liveUrl: "https://patents.google.com/patent/US4357089A/en",
      archiveUrl: "https://patents.google.com/patent/US4357089A/en",
      archiveDate: "2026-06-06",
      appliesTo:
        "Asahi/Pentax opposed mount-surface electrical contacts for diaphragm value and AUTO/MANUAL information, contact pairs, and lock pin/groove alignment",
      confidence: "high",
    },
    {
      ref: "pk-p3",
      sourceType: "patent",
      citation: 'US4939532A, "Mount apparatus of interchangeable lens camera." Accessed 2026-06-06.',
      liveUrl: "https://patents.google.com/patent/US4939532A/en",
      archiveUrl: "https://patents.google.com/patent/US4939532A/en",
      archiveDate: "2026-06-06",
      appliesTo:
        "Asahi/Pentax AF-era body mount, mount lock member, lens lock hole, retractable data/power contact pins, lens contact members, AF joint shaft, and lens driven shaft",
      confidence: "high",
    },
  ],

  openQuestions: [
    {
      issue:
        "US4017878A supports the three-claw bayonet/lock embodiment, US4357089A supports the KA opposed contact bank, and US4939532A supports the AF joint shaft plus data/power contacts; exact production throat, lug spans, contact pad dimensions/clocking, and later KAF/KAF2 terminal functions remain normalized to secondary imagery.",
      affectedFields: [
        "nominalThroatDiameterMm",
        "cameraSideFeatures",
        "lensSideFeatures",
        "contacts",
        "mechanicalCouplings",
        "body-lock-pin",
      ],
      candidateValues: [],
      resolution: "Upgrade to an official Pentax/Ricoh K-mount drawing or measured sample.",
    },
    {
      issue: "Contact count grows across KA (6) → KAF (7) → KAF2 (9); contactCount records the KA baseline.",
      affectedFields: ["contactCount"],
      candidateValues: [6, 7, 9],
      resolution: "Expose per-variant contact counts when variant selection drives the figure.",
    },
  ],
} satisfies MountSpecInput;

export default PENTAX_K_MOUNT;
