/**
 * Sony A mount SVG specification.
 *
 * The Minolta AF / Sony A SLR–SLT mount (Minolta Maxxum/Dynax, 1985; adopted by Sony in 2006): a
 * 44.5 mm flange focal distance and a 49.7 mm mount diameter. Modeled `base-only` — it carries BOTH a
 * mechanical AF screw-drive coupler and aperture-control arm AND an electronic contact block, like
 * the Pentax KAF family.
 *
 * Sourced scalars: flange focal distance 44.5 mm, 49.7 mm mount diameter, AF screw drive plus a
 * mechanical aperture arm plus electronic contacts [sa-1]. JAPB has no Sony A teardown, so the
 * bayonet lug count, the contact and coupling positions, and the lock/index clock positions are
 * photo-scaled (the contact bank is placed at the bottom by convention). Original Minolta bodies used
 * a 5-pin interface that later grew to 8 pins; eight is modeled.
 */

import type { MountSpecInput } from "../types/mount.js";
import { degListV, dirV, naV, unknownV, v } from "../optics/mount/authoring.js";

const W = ["sa-1"]; // Wikipedia

const SONY_A_MOUNT = {
  mountId: "sony-a",
  displayLabel: "Sony A",
  projectNote: "Minolta/Sony A SLR/SLT mount.",
  researchStatus: "researched",
  mvpStatus: "mvp_complete",
  mechanism: "bayonet",
  lockType: "sprung_detent",

  mvp: {
    requiredViews: ["camera_side_front_view", "lens_side_rear_view", "axial_register_schematic"],
    requirementLevels: {
      mvpRequired: ["flange_focal_distance_mm", "nominal_throat_diameter_mm", "camera_mount_outer_diameter_mm"],
      conditionalCoreRequired: ["bayonet_lugs", "lock_pin", "index_mark"],
      variantRequired: ["electrical_contacts", "af_screw_coupler", "aperture_arm"],
      mvpOptional: ["mount_screws"],
      referenceGrade: ["lug_ramp_undercut", "contact_pitch"],
    },
    profileModel: {
      baseProfileId: "sony-a/base",
      selectedMvpProfileId: "sony-a/base",
      variantStrategy: "base_only",
      variantProfiles: [
        {
          profileId: "sony-a/base",
          profileType: "base",
          appliesTo: "all Minolta AF / Sony A lenses and bodies (full-frame and APS-C DT), 1985–present",
          adds: [
            "bayonet lugs",
            "lock pin/notch",
            "mounting index",
            "AF screw-drive coupler",
            "mechanical aperture-control arm",
            "electrical contact block",
          ],
          removes: [],
          changes: ["original Minolta 5-pin interface grew to eight contacts"],
          cameraSideOverlayLayers: ["camera-side-variant-electrical", "camera-side-variant-mechanical"],
          lensSideOverlayLayers: ["lens-side-variant-electrical"],
          status: "researched",
          sourceRefs: W,
        },
      ],
    },
  },

  coreDimensions: {
    flangeFocalDistanceMm: v(44.5, "secondary", W),
    nominalThroatDiameterMm: v(49.7, "secondary", W),
    effectiveClearApertureMm: v(49.7, "secondary", W),
    cameraMountOuterDiameterMm: v(57, "photo_scaled", W),
    lensMountOuterDiameterMm: v(55, "photo_scaled", W),
    contactCount: v(8, "secondary", W),
  },

  lockGeometry: {
    insertionAngleDeg: v(0, "secondary", W),
    lockAngleDeg: unknownV(W),
    lockRotationDeg: unknownV(W),
    lockRotationDirection: dirV("unknown", "unknown", []),
  },

  cameraSideFeatures: [
    {
      featureId: "body-throat",
      featureType: "body_throat",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(24.85, "secondary", W),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "49.7 mm mount opening",
    },
    {
      featureId: "body-mount-ring",
      featureType: "mount_ring",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: v(0, "photo_scaled", W),
      endAngleDeg: v(360, "photo_scaled", W),
      innerRadiusMm: v(24.85, "secondary", W),
      outerRadiusMm: v(28.5, "photo_scaled", W),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "visible body mount ring",
    },
    {
      featureId: "body-slot-1",
      featureType: "bayonet_receiving_slot",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(30, "photo_scaled", W),
      startAngleDeg: v(10, "photo_scaled", W),
      endAngleDeg: v(50, "photo_scaled", W),
      innerRadiusMm: v(24.85, "photo_scaled", W),
      outerRadiusMm: v(27.5, "photo_scaled", W),
      depthMm: v(1.8, "photo_scaled", W),
      matesWith: "lens-lug-1",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "body-slot-2",
      featureType: "bayonet_receiving_slot",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(150, "photo_scaled", W),
      startAngleDeg: v(130, "photo_scaled", W),
      endAngleDeg: v(170, "photo_scaled", W),
      innerRadiusMm: v(24.85, "photo_scaled", W),
      outerRadiusMm: v(27.5, "photo_scaled", W),
      depthMm: v(1.8, "photo_scaled", W),
      matesWith: "lens-lug-2",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "body-slot-3",
      featureType: "bayonet_receiving_slot",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(290, "photo_scaled", W),
      startAngleDeg: v(270, "photo_scaled", W),
      endAngleDeg: v(310, "photo_scaled", W),
      innerRadiusMm: v(24.85, "photo_scaled", W),
      outerRadiusMm: v(27.5, "photo_scaled", W),
      depthMm: v(1.8, "photo_scaled", W),
      matesWith: "lens-lug-3",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "body-index-mark",
      featureType: "index_mark",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(29, "photo_scaled", W),
      depthMm: naV(),
      matesWith: "lens-index-mark",
      shapeNotes: "mounting index",
    },
    {
      featureId: "body-lock-pin",
      featureType: "lock_pin",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(270, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(25.5, "photo_scaled", W),
      depthMm: v(2, "photo_scaled", W),
      matesWith: "lens-lock-notch",
      shapeNotes: "lock pin (position unconfirmed)",
    },
  ],

  lensSideFeatures: [
    {
      featureId: "lens-throat",
      featureType: "lens_throat",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(23.85, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "rear opening",
    },
    {
      featureId: "lens-mount-ring",
      featureType: "lens_mount_ring",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: v(0, "photo_scaled", W),
      endAngleDeg: v(360, "photo_scaled", W),
      innerRadiusMm: v(23.85, "photo_scaled", W),
      outerRadiusMm: v(27.5, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "lens flange ring",
    },
    {
      featureId: "lens-lug-1",
      featureType: "bayonet_lug",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(30, "photo_scaled", W),
      startAngleDeg: v(10, "photo_scaled", W),
      endAngleDeg: v(50, "photo_scaled", W),
      innerRadiusMm: v(24.85, "photo_scaled", W),
      outerRadiusMm: v(27.5, "photo_scaled", W),
      thicknessMm: v(1.8, "photo_scaled", W),
      matesWith: "body-slot-1",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "lens-lug-2",
      featureType: "bayonet_lug",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(150, "photo_scaled", W),
      startAngleDeg: v(130, "photo_scaled", W),
      endAngleDeg: v(170, "photo_scaled", W),
      innerRadiusMm: v(24.85, "photo_scaled", W),
      outerRadiusMm: v(27.5, "photo_scaled", W),
      thicknessMm: v(1.8, "photo_scaled", W),
      matesWith: "body-slot-2",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "lens-lug-3",
      featureType: "bayonet_lug",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(290, "photo_scaled", W),
      startAngleDeg: v(270, "photo_scaled", W),
      endAngleDeg: v(310, "photo_scaled", W),
      innerRadiusMm: v(24.85, "photo_scaled", W),
      outerRadiusMm: v(27.5, "photo_scaled", W),
      thicknessMm: v(1.8, "photo_scaled", W),
      matesWith: "body-slot-3",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "lens-index-mark",
      featureType: "index_mark",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(28.5, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "body-index-mark",
      shapeNotes: "aligns with body index",
    },
    {
      featureId: "lens-lock-notch",
      featureType: "lock_notch",
      profileId: "sony-a/base",
      count: 1,
      centerAngleDeg: v(270, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(25.5, "photo_scaled", W),
      thicknessMm: v(2, "photo_scaled", W),
      matesWith: "body-lock-pin",
      shapeNotes: "receives body lock pin",
    },
  ],

  axialStack: [
    {
      planeId: "flange_datum",
      zPositionMm: v(0, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(57, "photo_scaled", W),
    },
    {
      planeId: "bayonet_lug_engagement",
      zPositionMm: v(1.2, "photo_scaled", W),
      thicknessMm: v(1.8, "photo_scaled", W),
      diameterMm: v(52, "photo_scaled", W),
    },
    {
      planeId: "electrical_contact_plane",
      zPositionMm: v(0.5, "photo_scaled", W),
      thicknessMm: v(0.5, "photo_scaled", W),
      diameterMm: v(46, "photo_scaled", W),
    },
    {
      planeId: "sensor_film_plane",
      zPositionMm: v(-44.5, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(43.3, "secondary", W),
    },
  ],

  contacts: [
    {
      side: "body",
      contactNo: 1,
      profileId: "sony-a/base",
      centerAngleDeg: v(152, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 2,
      profileId: "sony-a/base",
      centerAngleDeg: v(160, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 3,
      profileId: "sony-a/base",
      centerAngleDeg: v(168, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 4,
      profileId: "sony-a/base",
      centerAngleDeg: v(176, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 5,
      profileId: "sony-a/base",
      centerAngleDeg: v(184, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 6,
      profileId: "sony-a/base",
      centerAngleDeg: v(192, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 7,
      profileId: "sony-a/base",
      centerAngleDeg: v(200, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 8,
      profileId: "sony-a/base",
      centerAngleDeg: v(208, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "8th (original Minolta had 5)",
    },
    {
      side: "lens",
      contactNo: 1,
      profileId: "sony-a/base",
      centerAngleDeg: v(152, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 2,
      profileId: "sony-a/base",
      centerAngleDeg: v(160, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 3,
      profileId: "sony-a/base",
      centerAngleDeg: v(168, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 4,
      profileId: "sony-a/base",
      centerAngleDeg: v(176, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 5,
      profileId: "sony-a/base",
      centerAngleDeg: v(184, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 6,
      profileId: "sony-a/base",
      centerAngleDeg: v(192, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 7,
      profileId: "sony-a/base",
      centerAngleDeg: v(200, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 8,
      profileId: "sony-a/base",
      centerAngleDeg: v(208, "photo_scaled", W),
      centerRadiusMm: v(22.5, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "8th (original Minolta had 5)",
    },
  ],

  mechanicalCouplings: [
    {
      featureId: "af-screw-coupler",
      side: "body",
      profileId: "sony-a/base",
      centerAngleDeg: v(250, "photo_scaled", W),
      radiusMm: v(20, "photo_scaled", W),
      sizeOrTravel: "drive shaft",
      function: "mechanical (screw-drive) AF",
      compatibilityNotes: "non-SAM/SSM lenses",
    },
    {
      featureId: "aperture-control-arm",
      side: "body",
      profileId: "sony-a/base",
      centerAngleDeg: v(300, "photo_scaled", W),
      radiusMm: v(24, "photo_scaled", W),
      sizeOrTravel: "lever/arm",
      function: "mechanical aperture actuation",
      compatibilityNotes: "",
    },
  ],

  screwsGasketsBaffles: [
    {
      featureId: "body-mount-screws",
      featureType: "mount_screws",
      side: "body",
      count: v(5, "photo_scaled", W),
      pcdMm: v(54, "photo_scaled", W),
      diameterMm: v(2, "photo_scaled", W),
      centerAnglesDeg: degListV([30, 102, 174, 246, 318], "photo_scaled", W),
      shape: "round",
    },
  ],

  svgLayers: {
    mvpRequired: ["datum-axis", "camera-side-metal", "lens-side-metal", "axial-section", "uncertainty"],
    conditionalCoreRequired: ["clear-aperture", "camera-side-core-interface", "lens-side-core-interface"],
    variantRequired: [
      "camera-side-variant-electrical",
      "camera-side-variant-mechanical",
      "lens-side-variant-electrical",
      "lens-side-variant-mechanical",
    ],
  },

  sourceRefs: [
    {
      ref: "sa-1",
      sourceType: "secondary",
      citation: "“Minolta A-mount system,” Wikipedia. Accessed 2026-06-04.",
      liveUrl: "https://en.wikipedia.org/wiki/Minolta_A-mount_system",
      archiveUrl: "http://web.archive.org/web/20221225232256/https://en.wikipedia.org/wiki/Minolta_A-mount_system",
      archiveDate: "2022-12-25",
      appliesTo: "flange focal distance, 49.7 mm mount diameter, AF screw drive, aperture arm, electronic contacts",
      confidence: "medium",
    },
  ],

  openQuestions: [
    {
      issue: "Contact count grew from the original Minolta 5-pin to 8 pins; eight is modeled.",
      affectedFields: ["contactCount", "contacts"],
      candidateValues: [5, 8],
      resolution: "Model per-era contact counts if a generation selector is added.",
    },
    {
      issue:
        "Sony A lacks an archived teardown with clock positions: the bayonet lug count, the contact/coupling positions, and the lock/index clock positions are photo-scaled (contacts placed at the bottom by convention).",
      affectedFields: ["cameraSideFeatures", "lensSideFeatures", "contacts", "mechanicalCouplings", "lockGeometry"],
      candidateValues: [3, 4],
      resolution: "Upgrade to an official Minolta/Sony A mount drawing or measured sample.",
    },
  ],
} satisfies MountSpecInput;

export default SONY_A_MOUNT;
