/**
 * Sony E mount SVG specification.
 *
 * Sony's mirrorless mount (2010): an 18 mm flange focal distance and a 46.1 mm throat. The project
 * uses the `sony-fe` id for both APS-C (E) and full-frame (FE) lenses — format lives in `imageFormat`,
 * not in a separate mount. Modeled `base-only` — a single fully-electronic interface (no mechanical
 * couplings), with ten electrical contacts along the bottom of the mount.
 *
 * Sourced scalars: flange focal distance 18 mm, 46.1 mm throat, ten contacts [se-1]. Sony E lacks an
 * archived teardown with clock positions, so the bayonet lug count, the lock-pin position, and the
 * per-contact and index clock positions are photo-scaled and flagged in openQuestions (the contact
 * bank is placed at the documented bottom of the mount).
 */

import type { MountSpecInput } from "../types/mount.js";
import { degListV, dirV, naV, unknownV, v } from "../optics/mount/authoring.js";

const W = ["se-1"]; // Wikipedia

const SONY_E_MOUNT = {
  mountId: "sony-fe",
  displayLabel: "Sony E",
  projectNote: "Sony E mount; the sony-fe id covers both full-frame FE and APS-C E lenses.",
  researchStatus: "researched",
  mvpStatus: "mvp_complete",
  mechanism: "bayonet",
  lockType: "sprung_detent",

  mvp: {
    requiredViews: ["camera_side_front_view", "lens_side_rear_view", "axial_register_schematic"],
    requirementLevels: {
      mvpRequired: ["flange_focal_distance_mm", "nominal_throat_diameter_mm", "camera_mount_outer_diameter_mm"],
      conditionalCoreRequired: ["bayonet_lugs", "lock_pin", "index_mark"],
      variantRequired: ["electrical_contacts"],
      mvpOptional: ["mount_screws"],
      referenceGrade: ["lug_ramp_undercut", "contact_pitch"],
    },
    profileModel: {
      baseProfileId: "sony-fe/base",
      selectedMvpProfileId: "sony-fe/base",
      variantStrategy: "base_only",
      variantProfiles: [
        {
          profileId: "sony-fe/base",
          profileType: "base",
          appliesTo: "all Sony E / FE lenses and bodies (APS-C and full-frame), 2010–present",
          adds: ["bayonet lugs", "lock pin/notch", "mounting index", "ten-contact electrical block along the bottom"],
          removes: ["all mechanical couplings (fully electronic)"],
          changes: [],
          cameraSideOverlayLayers: ["camera-side-variant-electrical"],
          lensSideOverlayLayers: ["lens-side-variant-electrical"],
          status: "researched",
          sourceRefs: [...W, "se-p1"],
        },
      ],
    },
  },

  coreDimensions: {
    flangeFocalDistanceMm: v(18, "secondary", W),
    nominalThroatDiameterMm: v(46.1, "secondary", W),
    effectiveClearApertureMm: v(46.1, "secondary", W),
    cameraMountOuterDiameterMm: v(54, "photo_scaled", W),
    lensMountOuterDiameterMm: v(52, "photo_scaled", W),
    contactCount: v(10, "secondary", W),
  },

  lockGeometry: {
    insertionAngleDeg: v(0, "secondary", W),
    lockAngleDeg: unknownV(W),
    lockRotationDeg: unknownV(W),
    lockRotationDirection: dirV("unknown", "unknown", []),
  },

  cameraSideFeatures: [
    {
      featureId: "body-throat",
      featureType: "body_throat",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(23, "secondary", W),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "46.1 mm throat opening",
    },
    {
      featureId: "body-mount-ring",
      featureType: "mount_ring",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: v(0, "photo_scaled", W),
      endAngleDeg: v(360, "photo_scaled", W),
      innerRadiusMm: v(23, "secondary", W),
      outerRadiusMm: v(27, "photo_scaled", W),
      depthMm: naV(),
      matesWith: "",
      shapeNotes: "visible body mount ring",
    },
    {
      featureId: "body-slot-1",
      featureType: "bayonet_receiving_slot",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(30, "photo_scaled", W),
      startAngleDeg: v(10, "photo_scaled", W),
      endAngleDeg: v(50, "photo_scaled", W),
      innerRadiusMm: v(23, "photo_scaled", W),
      outerRadiusMm: v(25.5, "photo_scaled", W),
      depthMm: v(1.8, "photo_scaled", W),
      matesWith: "lens-lug-1",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "body-slot-2",
      featureType: "bayonet_receiving_slot",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(150, "photo_scaled", W),
      startAngleDeg: v(130, "photo_scaled", W),
      endAngleDeg: v(170, "photo_scaled", W),
      innerRadiusMm: v(23, "photo_scaled", W),
      outerRadiusMm: v(25.5, "photo_scaled", W),
      depthMm: v(1.8, "photo_scaled", W),
      matesWith: "lens-lug-2",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "body-slot-3",
      featureType: "bayonet_receiving_slot",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(290, "photo_scaled", W),
      startAngleDeg: v(270, "photo_scaled", W),
      endAngleDeg: v(310, "photo_scaled", W),
      innerRadiusMm: v(23, "photo_scaled", W),
      outerRadiusMm: v(25.5, "photo_scaled", W),
      depthMm: v(1.8, "photo_scaled", W),
      matesWith: "lens-lug-3",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "body-index-mark",
      featureType: "index_mark",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(27.5, "photo_scaled", W),
      depthMm: naV(),
      matesWith: "lens-index-mark",
      shapeNotes: "mounting index",
    },
    {
      featureId: "body-lock-pin",
      featureType: "lock_pin",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(270, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(24, "photo_scaled", W),
      depthMm: v(2, "photo_scaled", W),
      matesWith: "lens-lock-notch",
      shapeNotes: "lock pin (position unconfirmed)",
    },
  ],

  lensSideFeatures: [
    {
      featureId: "lens-throat",
      featureType: "lens_throat",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(0, "secondary", W),
      startAngleDeg: v(0, "secondary", W),
      endAngleDeg: v(360, "secondary", W),
      innerRadiusMm: v(0, "secondary", W),
      outerRadiusMm: v(22, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "rear opening",
    },
    {
      featureId: "lens-mount-ring",
      featureType: "lens_mount_ring",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: v(0, "photo_scaled", W),
      endAngleDeg: v(360, "photo_scaled", W),
      innerRadiusMm: v(22, "photo_scaled", W),
      outerRadiusMm: v(26, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "",
      shapeNotes: "lens flange ring",
    },
    {
      featureId: "lens-lug-1",
      featureType: "bayonet_lug",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(30, "photo_scaled", W),
      startAngleDeg: v(10, "photo_scaled", W),
      endAngleDeg: v(50, "photo_scaled", W),
      innerRadiusMm: v(23, "photo_scaled", W),
      outerRadiusMm: v(25.5, "photo_scaled", W),
      thicknessMm: v(1.8, "photo_scaled", W),
      matesWith: "body-slot-1",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "lens-lug-2",
      featureType: "bayonet_lug",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(150, "photo_scaled", W),
      startAngleDeg: v(130, "photo_scaled", W),
      endAngleDeg: v(170, "photo_scaled", W),
      innerRadiusMm: v(23, "photo_scaled", W),
      outerRadiusMm: v(25.5, "photo_scaled", W),
      thicknessMm: v(1.8, "photo_scaled", W),
      matesWith: "body-slot-2",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "lens-lug-3",
      featureType: "bayonet_lug",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(290, "photo_scaled", W),
      startAngleDeg: v(270, "photo_scaled", W),
      endAngleDeg: v(310, "photo_scaled", W),
      innerRadiusMm: v(23, "photo_scaled", W),
      outerRadiusMm: v(25.5, "photo_scaled", W),
      thicknessMm: v(1.8, "photo_scaled", W),
      matesWith: "body-slot-3",
      shapeNotes: "representative lug (count unconfirmed)",
    },
    {
      featureId: "lens-index-mark",
      featureType: "index_mark",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(0, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(26.5, "photo_scaled", W),
      thicknessMm: naV(),
      matesWith: "body-index-mark",
      shapeNotes: "aligns with body index",
    },
    {
      featureId: "lens-lock-notch",
      featureType: "lock_notch",
      profileId: "sony-fe/base",
      count: 1,
      centerAngleDeg: v(270, "photo_scaled", W),
      startAngleDeg: unknownV(W),
      endAngleDeg: unknownV(W),
      innerRadiusMm: unknownV(W),
      outerRadiusMm: v(24, "photo_scaled", W),
      thicknessMm: v(2, "photo_scaled", W),
      matesWith: "body-lock-pin",
      shapeNotes: "receives body lock pin",
    },
  ],

  axialStack: [
    {
      planeId: "flange_datum",
      zPositionMm: v(0, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(54, "photo_scaled", W),
    },
    {
      planeId: "bayonet_lug_engagement",
      zPositionMm: v(1, "photo_scaled", W),
      thicknessMm: v(1.8, "photo_scaled", W),
      diameterMm: v(49, "photo_scaled", W),
    },
    {
      planeId: "electrical_contact_plane",
      zPositionMm: v(0.5, "photo_scaled", W),
      thicknessMm: v(0.5, "photo_scaled", W),
      diameterMm: v(44, "photo_scaled", W),
    },
    {
      planeId: "sensor_film_plane",
      zPositionMm: v(-18, "secondary", W),
      thicknessMm: v(0, "secondary", W),
      diameterMm: v(43.3, "secondary", W),
    },
  ],

  contacts: [
    {
      side: "body",
      contactNo: 1,
      profileId: "sony-fe/base",
      centerAngleDeg: v(152, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 2,
      profileId: "sony-fe/base",
      centerAngleDeg: v(158, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 3,
      profileId: "sony-fe/base",
      centerAngleDeg: v(164, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 4,
      profileId: "sony-fe/base",
      centerAngleDeg: v(170, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 5,
      profileId: "sony-fe/base",
      centerAngleDeg: v(176, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 6,
      profileId: "sony-fe/base",
      centerAngleDeg: v(182, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 7,
      profileId: "sony-fe/base",
      centerAngleDeg: v(188, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 8,
      profileId: "sony-fe/base",
      centerAngleDeg: v(194, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 9,
      profileId: "sony-fe/base",
      centerAngleDeg: v(200, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "body",
      contactNo: 10,
      profileId: "sony-fe/base",
      centerAngleDeg: v(206, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0.4, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 1,
      profileId: "sony-fe/base",
      centerAngleDeg: v(152, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 2,
      profileId: "sony-fe/base",
      centerAngleDeg: v(158, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 3,
      profileId: "sony-fe/base",
      centerAngleDeg: v(164, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 4,
      profileId: "sony-fe/base",
      centerAngleDeg: v(170, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 5,
      profileId: "sony-fe/base",
      centerAngleDeg: v(176, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 6,
      profileId: "sony-fe/base",
      centerAngleDeg: v(182, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 7,
      profileId: "sony-fe/base",
      centerAngleDeg: v(188, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 8,
      profileId: "sony-fe/base",
      centerAngleDeg: v(194, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 9,
      profileId: "sony-fe/base",
      centerAngleDeg: v(200, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
    {
      side: "lens",
      contactNo: 10,
      profileId: "sony-fe/base",
      centerAngleDeg: v(206, "photo_scaled", W),
      centerRadiusMm: v(21, "photo_scaled", W),
      widthMm: v(1.3, "photo_scaled", W),
      heightMm: v(2.6, "photo_scaled", W),
      shape: "pad",
      protrusionMm: v(0, "photo_scaled", W),
      function: "",
    },
  ],

  mechanicalCouplings: [],

  screwsGasketsBaffles: [
    {
      featureId: "body-mount-screws",
      featureType: "mount_screws",
      side: "body",
      count: v(4, "photo_scaled", W),
      pcdMm: v(50, "photo_scaled", W),
      diameterMm: v(2, "photo_scaled", W),
      centerAnglesDeg: degListV([45, 135, 225, 315], "photo_scaled", W),
      shape: "round",
    },
  ],

  svgLayers: {
    mvpRequired: ["datum-axis", "camera-side-metal", "lens-side-metal", "axial-section", "uncertainty"],
    conditionalCoreRequired: ["clear-aperture", "camera-side-core-interface", "lens-side-core-interface"],
    variantRequired: ["camera-side-variant-electrical", "lens-side-variant-electrical"],
  },

  sourceRefs: [
    {
      ref: "se-1",
      sourceType: "secondary",
      citation: "“Sony E-mount,” Wikipedia. Accessed 2026-06-04.",
      liveUrl: "https://en.wikipedia.org/wiki/Sony_E-mount",
      archiveUrl: "http://web.archive.org/web/20230522152822/https://en.wikipedia.org/wiki/Sony_E-mount",
      archiveDate: "2023-05-22",
      appliesTo: "flange focal distance, 46.1 mm throat, ten contacts, APS-C/full-frame",
      confidence: "medium",
    },
    {
      ref: "se-p1",
      sourceType: "patent",
      citation:
        "US9392150B2, Sony E/FE body mount, contact-pin, latch and full-frame geometry patent. Accessed 2026-06-06.",
      liveUrl: "https://www.freepatentsonline.com/9392150.html",
      archiveUrl: "https://www.freepatentsonline.com/9392150.html",
      archiveDate: "2026-06-06",
      appliesTo: "Sony E/FE mount and contact-pin/latch research lead",
      confidence: "medium",
    },
  ],

  openQuestions: [
    {
      issue:
        "Sony E lacks an archived teardown with clock positions: the bayonet lug count, the lock-pin position, the mounting-index position, and the per-contact clock positions are photo-scaled (the contact bank is placed at the documented bottom of the mount).",
      affectedFields: ["cameraSideFeatures", "lensSideFeatures", "contacts", "lockGeometry"],
      candidateValues: [3, 4],
      resolution: "Upgrade to an official Sony E mount drawing or measured sample.",
    },
  ],
} satisfies MountSpecInput;

export default SONY_E_MOUNT;
