import type { LensDataInput } from "../../types/optics.js";

/**
 * ╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
 * ║ LENS DATA — FUJIFILM SUPER EBC FUJINON 7.1-28.4mm f/2-2.8 (Fujifilm X10)                            ║
 * ╠══════════════════════════════════════════════════════════════════════════════════════════════════════╣
 * ║ Data source: US 2014/0133036 A1, Example 1 (Fujifilm Corporation; Taiga Noda and Michio Cho).       ║
 * ║ Four-group positive-negative-positive-positive zoom; 11 elements / 9 groups; 5 aspherical surfaces. ║
 * ║ Production correlation is strong but not exact: the X10 is marketed as 7.1-28.4mm f/2-2.8 with      ║
 * ║ 11 elements / 9 groups, three aspherical elements, two ED elements, and lens-shift stabilization,   ║
 * ║ but Fujifilm describes six production aspherical surfaces while Example 1 publishes five.           ║
 * ║                                                                                                      ║
 * ║ Zoom variable gaps: DD3, DD9, DD19, and the normalized rear air gap at surface 21.                   ║
 * ║ DD9 moves the stop with G3 while preserving the patent's fixed 0.85 mm STO-to-S11 spacing.           ║
 * ║ G2 and G4 reverse direction around the middle state; all three published positions are retained.    ║
 * ║ Focus status: NO_INTERNAL_RECONSTRUCTION. The patent publishes infinity-focus zoom states only.      ║
 * ║ Every focus pair is therefore identical; no close-focus group motion is invented.                    ║
 * ║                                                                                                      ║
 * ║ No uniform scale was applied. Marketing focal length/aperture fields remain separate from the        ║
 * ║ patent/computed design values. nominalFno uses the modeled values generated by a common              ║
 * ║ 4.8047662947 mm stop radius rather than the rounded Table 3 f-numbers.                                ║
 * ║                                                                                                      ║
 * ║ The plane-parallel PP cover/filter surrogate (S22-S23) is omitted. Its paraxial optical thickness    ║
 * ║ is folded into the rear air gap as DD21 + 2.14 / 1.516798 + DD23.                                    ║
 * ║                                                                                                      ║
 * ║ The patent's asphere equation uses sqrt(1 - KA·(h/R)^2); coefficients below use K = KA - 1.          ║
 * ║ Nonzero odd radial powers A3, A5, A7, A9, and A11 are transcribed directly.                           ║
 * ║                                                                                                      ║
 * ║ Semi-diameters are modeled values, not patent data. They began as exact-trace envelopes across all    ║
 * ║ zoom states and were compared with the wide-position Figure 1 section. The G1 apertures were reduced ║
 * ║ to follow the illustrated blank outline, then rechecked for edge thickness, rim slope, conic domain, ║
 * ║ shared-gap intrusion, ray containment, and render-trim policy. The S15/S16 apertures are limited      ║
 * ║ by the 2.10 mm shared air gap rather than by obsolete sd/|R| or element-ratio rules.                  ║
 * ║                                                                                                      ║
 * ║ lensMounts uses the canonical fixed-lens-camera id. imageFormat is intentionally omitted because     ║
 * ║ the current taxonomy has no 2/3-inch-type id.                                                         ║
 * ╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝
 */

const LENS_DATA = {
  key: "fujifilm-x10-7-1-28-4-f2-2-8",
  maker: "Fujifilm",
  name: "FUJIFILM SUPER EBC FUJINON 7.1-28.4mm f/2-2.8 (Fujifilm X10)",
  subtitle: "US 2014/0133036 A1 Example 1 — strong X10 correlation; not asserted as the exact production prescription",
  specs: [
    "11 ELEMENTS / 9 GROUPS",
    "DESIGN f = 7.342-27.682 mm",
    "MODELED F/2.064-2.875",
    "2ω = 79.65°-21.99°",
    "5 ASPHERICAL SURFACES / 3 ELEMENTS",
  ],

  focalLengthMarketing: [7.1, 28.4],
  focalLengthDesign: [7.3421119019253425, 27.68224301655568],
  apertureMarketing: 2,
  apertureDesign: 2.0635977497452442,
  lensMounts: ["fixed-lens-camera"],
  patentNumber: "US 2014/0133036 A1",
  patentAuthors: ["Taiga Noda", "Michio Cho"],
  patentAssignees: ["Fujifilm Corporation"],
  patentYear: 2014,
  elementCount: 11,
  groupCount: 9,

  elements: [
    {
      id: 1,
      name: "L11",
      label: "G1 front element",
      type: "Negative Meniscus",
      nd: 1.945945,
      vd: 17.98,
      fl: -99.11608144774293,
      glass: "FDS18 (HOYA; exact 946180 coordinate match)",
      apd: false,
      role: "High-index negative member of the cemented positive first group.",
      cemented: "D1",
    },
    {
      id: 2,
      name: "L12",
      label: "G1 rear element",
      type: "Positive Meniscus",
      nd: 1.834807,
      vd: 42.72,
      fl: 34.64514165115275,
      glass: "S-LAH55 (OHARA; exact 835427 coordinate match)",
      apd: false,
      role: "Strong positive member that makes the cemented first group net positive.",
      cemented: "D1",
    },
    {
      id: 3,
      name: "L21",
      label: "G2 front element",
      type: "Negative Meniscus",
      nd: 1.882997,
      vd: 40.76,
      fl: -10.991471611227626,
      glass: "S-LAH58 (OHARA; exact 883408 coordinate match)",
      apd: false,
      role: "Strong negative front member of the variator group.",
    },
    {
      id: 4,
      name: "L22",
      label: "G2 central asphere",
      type: "Biconcave Negative (2× Asph)",
      nd: 1.583129,
      vd: 59.37,
      fl: -24.231001623370823,
      glass: "S-BAL42 (OHARA; exact 583594 coordinate match)",
      apd: false,
      role: "Double-aspherical biconcave element governing G2 power and zoom aberration balance.",
    },
    {
      id: 5,
      name: "L23",
      label: "G2 rear element",
      type: "Biconvex Positive",
      nd: 1.92286,
      vd: 20.88,
      fl: 25.766590533356887,
      glass: "N-SF66 (SCHOTT; exact 923209 coordinate match)",
      apd: false,
      role: "Positive rear member that moderates the net negative power of G2.",
    },
    {
      id: 6,
      name: "L31",
      label: "G3 front asphere",
      type: "Biconvex Positive (1× Asph)",
      nd: 1.803603,
      vd: 40.28,
      fl: 16.811764372806998,
      glass: "Unmatched (nd=1.803603, νd=40.28)",
      apd: false,
      role: "Front positive member of the moving third group and its principal entrance asphere.",
    },
    {
      id: 7,
      name: "L32",
      label: "G3 cemented positive element",
      type: "Biconvex Positive",
      nd: 1.592824,
      vd: 68.62,
      fl: 11.902469333152276,
      glass: "FCD515 (HOYA) / 593686 ED phosphate-crown class",
      apd: "inferred",
      apdNote: "Catalog-derived FCD515 match; dPgF = +0.0192.",
      dPgF: 0.0192,
      nC: 1.59021,
      nF: 1.59884,
      ng: 1.60355,
      role: "ED-class positive member of the cemented L32/L33 chromatic pair.",
      cemented: "D2",
    },
    {
      id: 8,
      name: "L33",
      label: "G3 cemented negative element",
      type: "Biconcave Negative",
      nd: 1.698947,
      vd: 30.13,
      fl: -7.743375258922189,
      glass: "S-TIM35 (OHARA; exact 699301 coordinate match)",
      apd: false,
      role: "Dense-flint negative partner; the isolated cemented pair is net negative.",
      cemented: "D2",
    },
    {
      id: 9,
      name: "L34",
      label: "G3 negative asphere",
      type: "Negative Meniscus (2× Asph)",
      nd: 1.803603,
      vd: 40.28,
      fl: -25.309844064066173,
      glass: "Unmatched (nd=1.803603, νd=40.28)",
      apd: false,
      role: "Double-aspherical negative meniscus used for fast-aperture and peripheral correction.",
    },
    {
      id: 10,
      name: "L35",
      label: "G3 rear ED element",
      type: "Biconvex Positive",
      nd: 1.496999,
      vd: 81.54,
      fl: 15.209674080099681,
      glass: "S-FPL51 (OHARA)",
      apd: "inferred",
      apdNote: "Catalog-derived S-FPL51 match; dPgF = +0.0280.",
      dPgF: 0.028,
      nC: 1.495136,
      nF: 1.501231,
      ng: 1.504507,
      role: "Very-low-dispersion positive rear member completing the net-positive third group.",
    },
    {
      id: 11,
      name: "L41",
      label: "Fourth-group element",
      type: "Positive Meniscus",
      nd: 1.48749,
      vd: 70.24,
      fl: 48.633349972496035,
      glass: "S-FSL5 (OHARA; exact 487702 coordinate match)",
      apd: false,
      role: "Single positive rear group; the patent identifies G4 as a possible quick-focus group.",
    },
  ],

  surfaces: [
    { label: "1", R: 38.6302, d: 1.11, nd: 1.945945, elemId: 1, sd: 8.8 },
    { label: "2", R: 26.976, d: 4.3, nd: 1.834807, elemId: 2, sd: 8.6 },
    { label: "3", R: 371.8467, d: 0.4, nd: 1, elemId: 0, sd: 8.5 },
    { label: "4", R: 66.7099, d: 1, nd: 1.882997, elemId: 3, sd: 9 },
    { label: "5", R: 8.4132, d: 4.8, nd: 1, elemId: 0, sd: 6.8 },
    { label: "6A", R: -19.0605, d: 1, nd: 1.583129, elemId: 4, sd: 6.3 },
    { label: "7A", R: 55.6768, d: 0.4, nd: 1, elemId: 0, sd: 6.2 },
    { label: "8", R: 24.9067, d: 2.5, nd: 1.92286, elemId: 5, sd: 6.2 },
    { label: "9", R: -499.8687, d: 19.85, nd: 1, elemId: 0, sd: 6 },
    { label: "STO", R: 1e15, d: 0.85, nd: 1, elemId: 0, sd: 4.80476629466163 },
    { label: "11A", R: 14.2177, d: 2.5, nd: 1.803603, elemId: 6, sd: 5.5 },
    { label: "12", R: -250.1461, d: 0.1, nd: 1, elemId: 0, sd: 5.4 },
    { label: "13", R: 10.009, d: 3.41, nd: 1.592824, elemId: 7, sd: 5.2 },
    { label: "14", R: -20.884, d: 0.7, nd: 1.698947, elemId: 8, sd: 4.9 },
    { label: "15", R: 7.4062, d: 2.1, nd: 1, elemId: 0, sd: 3.85 },
    { label: "16A", R: -10, d: 0.9, nd: 1.803603, elemId: 9, sd: 3.85 },
    { label: "17A", R: -20.4609, d: 0.1, nd: 1, elemId: 0, sd: 4.2 },
    { label: "18", R: 27.8958, d: 2.9, nd: 1.496999, elemId: 10, sd: 4.35 },
    { label: "19", R: -10.0111, d: 6.77, nd: 1, elemId: 0, sd: 4.5 },
    { label: "20", R: 14.4956, d: 2.8, nd: 1.48749, elemId: 11, sd: 5.7 },
    { label: "21", R: 34.9421, d: 6.120866839223153, nd: 1, elemId: 0, sd: 5.7 },
  ],

  asph: {
    "6A": {
      K: -5.148111,
      A3: 1.150223e-3,
      A4: -6.585878e-4,
      A5: 1.685927e-4,
      A6: -1.904884e-6,
      A7: -5.155217e-6,
      A8: 4.256246e-8,
      A9: 1.426374e-7,
      A10: -1.188533e-8,
      A12: 0,
      A14: 0,
      A16: 0,
      A18: 0,
      A20: 0,
    },
    "7A": {
      K: -10.950295,
      A3: 9.646437e-4,
      A4: -4.885791e-4,
      A5: 1.432608e-4,
      A6: -3.875323e-6,
      A7: -4.241185e-6,
      A8: 9.597971e-8,
      A9: 1.081173e-7,
      A10: -9.188089e-9,
      A12: 0,
      A14: 0,
      A16: 0,
      A18: 0,
      A20: 0,
    },
    "11A": {
      K: 2.660046,
      A3: -4.036084e-5,
      A4: -5.899152e-5,
      A5: -3.723504e-5,
      A6: 1.055957e-5,
      A7: -9.760767e-7,
      A8: -4.976513e-7,
      A9: 1.682713e-7,
      A10: -2.503631e-8,
      A11: 2.157418e-9,
      A12: -1.06085e-10,
      A14: 0,
      A16: 0,
      A18: 0,
      A20: 0,
    },
    "16A": {
      K: -9.971192,
      A3: -7.781902e-4,
      A4: -8.305061e-4,
      A5: -2.230827e-5,
      A6: -1.358257e-5,
      A7: 1.334413e-5,
      A8: 2.007369e-6,
      A9: -1.003647e-6,
      A10: -1.949607e-7,
      A11: 8.686077e-8,
      A12: -7.236734e-9,
      A14: 0,
      A16: 0,
      A18: 0,
      A20: 0,
    },
    "17A": {
      K: -6.65845,
      A3: -8.424122e-4,
      A4: 7.988741e-4,
      A5: -2.765325e-4,
      A6: 4.453843e-5,
      A7: 2.895206e-6,
      A8: 3.897227e-7,
      A9: -7.739047e-7,
      A10: 1.551732e-7,
      A11: -1.172742e-8,
      A12: 3.933323e-10,
      A14: 0,
      A16: 0,
      A18: 0,
      A20: 0,
    },
  },

  var: {
    "3": [
      [0.4, 0.4],
      [9.03, 9.03],
      [16.3, 16.3],
    ],
    "9": [
      [19.85, 19.85],
      [8.57, 8.57],
      [1.7, 1.7],
    ],
    "19": [
      [6.77, 6.77],
      [10, 10],
      [18.2, 18.2],
    ],
    "21": [
      [6.120866839223153, 6.120866839223153],
      [7.570866839223153, 7.570866839223153],
      [6.690866839223153, 6.690866839223153],
    ],
  },

  varLabels: [
    ["3", "DD3"],
    ["9", "DD9"],
    ["19", "DD19"],
    ["21", "BF (air-eq.)"],
  ],

  zoomPositions: [7.34, 14.25, 27.68],
  zoomStep: 0.004,
  zoomLabels: ["Wide", "Tele"],

  groups: [
    { text: "G1 (+)", fromSurface: "1", toSurface: "3" },
    { text: "G2 (-)", fromSurface: "4", toSurface: "9" },
    { text: "G3 (+ / IS)", fromSurface: "11A", toSurface: "19" },
    { text: "G4 (+)", fromSurface: "20", toSurface: "21" },
  ],

  doublets: [
    { text: "D1", fromSurface: "1", toSurface: "3" },
    { text: "D2", fromSurface: "13", toSurface: "15" },
  ],

  closeFocusM: 0.5,
  focusDescription:
    "NO_INTERNAL_RECONSTRUCTION: only published infinity-focus zoom states are modeled. The required close-focus metadata uses the X10 ordinary wide-angle 0.50 m limit; the separate 0.01 m Super Macro mode is not reconstructed.",

  nominalFno: [2.0635977497452442, 2.356517333967113, 2.8750952795678733],
  fstopSeries: [2, 2.8, 4, 5.6, 8, 11],
  maxFstop: 11,

  yScFill: 0.42,
} satisfies LensDataInput;

export default LENS_DATA;
