import type { LensDataInput } from "../../types/optics.js";

/**
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║           LENS DATA — KONICA HEXANON 38mm f/2.8                    ║
 * ╠══════════════════════════════════════════════════════════════════════╣
 * ║  Data source: US 3,615,126, Embodiment I / Claim 2                 ║
 * ║  Tadashi Kojima, Konishiroku Photo Industry Co., Ltd.              ║
 * ║  Rear-stop compact-camera Tessar derivative.                       ║
 * ║  4 elements / 3 groups, all spherical.                             ║
 * ║  Focus: unit focus; all glass groups move together.                ║
 * ║                                                                    ║
 * ║  NOTE ON SCALING:                                                  ║
 * ║    Patent prescription is normalized to f = 1.0. All radii,        ║
 * ║    thicknesses, air spaces, and inferred semi-diameters are scaled ║
 * ║    ×38.0 to the production Konica C35 38mm nominal focal length.   ║
 * ║    The rounded prescription traces to EFL = 38.3227mm.             ║
 * ║                                                                    ║
 * ║  NOTE ON BACK FOCUS:                                               ║
 * ║    The patent table states fB = 0.7658f, but a direct paraxial      ║
 * ║    y-nu trace of the rounded prescription gives BFD = 0.79030f.    ║
 * ║    This file uses the computed BFD so the transcribed prescription ║
 * ║    is paraxially focused in the renderer.                          ║
 * ║                                                                    ║
 * ║  NOTE ON SEMI-DIAMETERS:                                           ║
 * ║    The patent does not publish clear semi-diameters. Values below  ║
 * ║    were inferred from on-axis f/2.8 entrance-pupil geometry, rear   ║
 * ║    stop placement, and mechanical clearance checks. The rear-group ║
 * ║    SDs are constrained chiefly by the very small d4 air gap.       ║
 * ║                                                                    ║
 * ║  IMPORTANT: This file describes ONLY the optical design:           ║
 * ║    ✓ Glass elements and surfaces, front element to image plane     ║
 * ║    ✓ Rear aperture stop and unit-focus back-focus gap              ║
 * ║    ✗ No sensor glass, filters, shutter blades, or camera body      ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 */

const LENS_DATA = {
  key: "konica-hexanon-38mm-f28",
  maker: "Konica",
  name: "KONICA HEXANON 38mm f/2.8 (Konica C35)",
  subtitle: "US 3,615,126 Embodiment I — Kojima / Konishiroku",
  specs: ["4 ELEMENTS / 3 GROUPS", "f = 38mm nominal", "F/2.8", "2ω ≈ 59°", "REAR STOP"],

  focalLengthMarketing: 38,
  focalLengthDesign: 38.3227,
  apertureMarketing: 2.8,
  apertureDesign: 2.824,
  lensMounts: ["fixed-lens-camera"],
  imageFormat: "135-full-frame",
  patentNumber: "US 3,615,126",
  patentAuthors: ["Tadashi Kojima"],
  patentAssignees: ["Konica Minolta, Inc."],
  patentYear: 1971,
  elementCount: 4,
  groupCount: 3,

  elements: [
    {
      id: 1,
      name: "L1",
      label: "Element 1",
      type: "Positive Meniscus",
      nd: 1.8042,
      vd: 46.6,
      fl: 22.37,
      glass: "S-LAH65V / TAF3 class (OHARA/Hoya, 804/466)",
      apd: false,
      role: "High-index positive front meniscus; reduces Petzval sum while allowing a relatively large front radius.",
    },
    {
      id: 2,
      name: "L2",
      label: "Element 2",
      type: "Biconcave Negative",
      nd: 1.7569,
      vd: 31.7,
      fl: -13.85,
      glass: "E-LAF11 (Hikari, nearest modern catalog equivalent to patent 757/317)",
      apd: false,
      role: "Weak-front biconcave diverger; controls coma generated by the rear-stop compact layout.",
    },
    {
      id: 3,
      name: "L3",
      label: "Element 3",
      type: "Negative Meniscus",
      nd: 1.72825,
      vd: 28.3,
      fl: -24.11,
      glass: "S-TIH10 / E-FD10 / N-SF10 class (728/283)",
      apd: false,
      cemented: "D1",
      role: "Negative member of the rear cemented doublet; works with the high-index L4 at the r6 cemented interface.",
    },
    {
      id: 4,
      name: "L4",
      label: "Element 4",
      type: "Biconvex Positive",
      nd: 1.8306,
      vd: 26.5,
      fl: 11.57,
      glass: "Unmatched (high-index dense flint, 831/265)",
      apd: false,
      cemented: "D1",
      role: "Strong positive rear doublet member; its high index and r6 cemented surface are central to coma and Petzval control.",
    },
  ],

  surfaces: [
    { label: "1", R: 12.5704, d: 3.8, nd: 1.8042, elemId: 1, sd: 8.7 },
    { label: "2", R: 36.0962, d: 1.026, nd: 1.0, elemId: 0, sd: 7.25 },
    { label: "3", R: -108.4482, d: 1.71, nd: 1.7569, elemId: 2, sd: 6.95 },
    { label: "4", R: 11.6812, d: 1.596, nd: 1.0, elemId: 0, sd: 6.1 },
    { label: "5", R: 45.657, d: 0.95, nd: 1.72825, elemId: 3, sd: 6.1 },
    { label: "6", R: 12.5704, d: 3.8, nd: 1.8306, elemId: 4, sd: 6.75 },
    { label: "7", R: -35.2222, d: 2.204, nd: 1.0, elemId: 0, sd: 7.0 },
    { label: "STO", R: 1e15, d: 27.8273158541, nd: 1.0, elemId: 0, sd: 4.9273265045 },
  ],

  asph: {},
  var: {
    STO: [27.8273158541, 29.4258861114],
  },
  varLabels: [["STO", "BF"]],

  groups: [
    { text: "G1", fromSurface: "1", toSurface: "2" },
    { text: "G2", fromSurface: "3", toSurface: "4" },
    { text: "G3", fromSurface: "5", toSurface: "7" },
  ],
  doublets: [{ text: "D1", fromSurface: "5", toSurface: "7" }],

  focusDescription:
    "Unit focus: all four glass elements translate together; the data file varies only the back-focus gap from infinity to 1.0m.",
  closeFocusM: 1.0,
  nominalFno: 2.8,
  fstopSeries: [2.8, 4, 5.6, 8, 11, 16, 22],

  // Rear-stop compact lenses vignette substantially off-axis at full aperture; use a conservative off-axis bundle for display.
  offAxisFieldFrac: 0.33,
  scFill: 0.58,
  yScFill: 0.34,
} satisfies LensDataInput;

export default LENS_DATA;
