import type { LensDataInput } from "../../types/optics.js";

/**
 * ╔══════════════════════════════════════════════════════════════════════════════╗
 * ║ LENS DATA — CANON EF 135mm f/2.8 Soft Focus                               ║
 * ╠══════════════════════════════════════════════════════════════════════════════╣
 * ║ Source: US 4,826,301, Numerical Example 4 (Keiji Ikemori / Canon).        ║
 * ║ Production correlation: Canon Camera Museum, EF135mm f/2.8 Soft Focus.    ║
 * ║ 7 elements / 6 groups; one glass-molded aspherical surface (7A).          ║
 * ║                                                                            ║
 * ║ FOCUS STATUS — CONSTRAINED_RECONSTRUCTION                                 ║
 * ║ The patent states that III-1 (cemented L5+L6) moves rearward for closer   ║
 * ║ focus but publishes no ordinary-focus spacing table. The close endpoint   ║
 * ║ below is independently solved for Canon's 1.3 m MFD (measured from the    ║
 * ║ focal plane): III-1 travel = 9.007510523 mm, with D9 + D12 = 25.80 mm     ║
 * ║ conserved and the image plane fixed.                                      ║
 * ║                                                                            ║
 * ║ SOFT-FOCUS CONTROL                                                         ║
 * ║ Patent-published normal -> soft spacings are kept under aberrationControl, ║
 * ║ not focus var. L4 moves rearward 9.20 mm; III-1 moves forward 2.40 mm     ║
 * ║ for image-shift compensation. D6 + D8 = 18.37 mm and D9 + D12 = 25.80 mm ║
 * ║ in both published control states.                                          ║
 * ║                                                                            ║
 * ║ APERTURE MODEL                                                             ║
 * ║ Example 4 publishes f/3.4 in normal photography and f/2.8 in soft focus, ║
 * ║ but no stop diameter or clear apertures. nominalFno = 2.8 intentionally   ║
 * ║ defines the full-open stop/pupil reference. L4 clear radii are inferred   ║
 * ║ from the soft-state f/2.8 axial bundle; at the normal L4 position they     ║
 * ║ limit the modeled axial bundle to f/3.341365, consistent with the patent's ║
 * ║ rounded f/3.4. This preserves the patent's state-dependent beam-limiting   ║
 * ║ mechanism instead of pretending the diaphragm itself changes.              ║
 * ║                                                                            ║
 * ║ SEMI-DIAMETERS                                                             ║
 * ║ The patent publishes none. R7A/R8 are the inferred f/2.8 soft-state clear ║
 * ║ radii. STO is the exact full-open stop radius generated by the current     ║
 * ║ nominalFno semantics in the normal base state. Other SDs are conservative ║
 * ║ ray-envelope values checked against axial bundles, the default 60%-field  ║
 * ║ off-axis fan, the 9.1-degree chief ray, close focus, and Figure 10.         ║
 * ║                                                                            ║
 * ║ GLASS / SPECTRAL DATA                                                      ║
 * ║ The patent supplies d-line nd/vd only and no per-element nC, nF, ng, PgF, ║
 * ║ or dPgF. Vendor identity is not established; class/code labels are used.  ║
 * ║ L2 uses a qualified SK16-class coefficient proxy within the catalog guard; ║
 * ║ the patent coordinates remain authoritative and supplier-neutral.          ║
 * ║                                                                            ║
 * ║ No scaling is applied. No sensor cover, filter, dummy plane, or mechanical║
 * ║ component is included. R14.d is the independently computed normal-state   ║
 * ║ paraxial BFD to the fixed image plane.                                     ║
 * ╚══════════════════════════════════════════════════════════════════════════════╝
 *
 * Manufacturer source:
 * https://global.canon/en/c-museum/product/ef268.html
 * Canon minimum-focus-distance reference-plane convention:
 * https://cam.start.canon/en/C007/manual/html/UG-02_BasicShooting_0110.html
 */

const LENS_DATA = {
  /* ── Identity ── */
  key: "canon-ef-135mm-f28-soft-focus",
  maker: "Canon",
  name: "CANON EF 135mm f/2.8 Soft Focus",
  subtitle: "US 4,826,301 — Numerical Example 4 production correlation",
  specs: [
    "7 ELEMENTS / 6 GROUPS",
    "135.043 mm DESIGN EFL",
    "f/3.341 SHARP / f/2.8 SOFT",
    "18.2° FULL FIELD",
    "1 GLASS-MOLDED ASPHERE",
    "REAR FOCUS / SOFT-FOCUS CONTROL",
  ],

  focalLengthMarketing: 135,
  focalLengthDesign: 135.04315036977448,
  apertureMarketing: 2.8,
  apertureDesign: 2.8,
  lensMounts: ["canon-ef"],
  imageFormat: "135-full-frame",
  patentNumber: "US 4,826,301",
  patentAuthors: ["Keiji Ikemori"],
  patentAssignees: ["Canon Inc."],
  patentYear: 1989,
  elementCount: 7,
  groupCount: 6,
  projection: {
    kind: "rectilinear",
    fullFieldDeg: 18.2,
    maxTraceFieldDeg: 9.1,
  },

  /* ── Elements ── */
  elements: [
    {
      id: 1,
      name: "L1",
      label: "Element 1",
      type: "Biconvex Positive",
      nd: 1.62299,
      vd: 58.2,
      fl: 79.82300614130565,
      glass: "623582 class (catalog vendor unresolved)",
      role: "Front positive collector in component I.",
    },
    {
      id: 2,
      name: "L2",
      label: "Element 2",
      type: "Biconvex Positive",
      nd: 1.62299,
      vd: 60.7,
      fl: 119.67993390924296,
      glass: "SK16-class coefficient proxy (patent 623607; production supplier unspecified)",
      role: "Second positive element in component I; the printed patent index/Abbe pair is preserved.",
    },
    {
      id: 3,
      name: "L3",
      label: "Element 3",
      type: "Biconcave Negative",
      nd: 1.80518,
      vd: 25.4,
      fl: -98.02147704110979,
      glass: "805254 class (catalog vendor unresolved)",
      role: "Negative corrector completing positive front component I.",
    },
    {
      id: 4,
      name: "L4",
      label: "Element 4",
      type: "Negative Meniscus (1× Asph)",
      nd: 1.58313,
      vd: 59.4,
      fl: -421.0026167597842,
      glass: "583594 class (catalog vendor unresolved)",
      role: "Aspherical forward-convex meniscus; independent soft-focus mover (component II).",
    },
    {
      id: 5,
      name: "L5",
      label: "Element 5",
      type: "Positive Meniscus",
      nd: 1.7552,
      vd: 27.5,
      fl: 99.25034099317321,
      glass: "755275 class (catalog vendor unresolved)",
      role: "Positive member of the cemented rear-focus doublet III-1.",
      cemented: "III-1",
    },
    {
      id: 6,
      name: "L6",
      label: "Element 6",
      type: "Biconcave Negative",
      nd: 1.54072,
      vd: 47.2,
      fl: -36.882006964113216,
      glass: "541472 class (catalog vendor unresolved)",
      role: "Negative member of the cemented rear-focus doublet III-1; the assembled doublet is net negative.",
      cemented: "III-1",
    },
    {
      id: 7,
      name: "L7",
      label: "Element 7",
      type: "Biconvex Positive",
      nd: 1.48749,
      vd: 70.2,
      fl: 81.89968380293107,
      glass: "487702 class (catalog vendor unresolved)",
      role: "Stationary positive rear sub-component III-2.",
    },
  ],

  /* ── Surface prescription: US 4,826,301 Numerical Example 4 ── */
  surfaces: [
    { label: "1", R: 50.67, d: 9.0, nd: 1.62299, elemId: 1, sd: 24.2 },
    { label: "2", R: -2495.01, d: 0.15, nd: 1.0, elemId: 0, sd: 23.6 },
    { label: "3", R: 92.46, d: 5.5, nd: 1.62299, elemId: 2, sd: 22.8 },
    { label: "4", R: -376.32, d: 1.71, nd: 1.0, elemId: 0, sd: 22.2 },
    { label: "5", R: -195.53, d: 2.2, nd: 1.80518, elemId: 3, sd: 21.4 },
    { label: "6", R: 133.01, d: 0.8, nd: 1.0, elemId: 0, sd: 20.2 },
    { label: "7A", R: 30.44, d: 2.6, nd: 1.58313, elemId: 4, sd: 15.675574 },
    { label: "8", R: 26.23, d: 17.57, nd: 1.0, elemId: 0, sd: 14.574842 },
    { label: "STO", R: 1e15, d: 6.0, nd: 1.0, elemId: 0, sd: 14.114355 },
    { label: "10", R: -93.04, d: 2.7, nd: 1.7552, elemId: 5, sd: 13.4 },
    { label: "11", R: -42.03, d: 1.39, nd: 1.54072, elemId: 6, sd: 13.3 },
    { label: "12", R: 38.39, d: 19.8, nd: 1.0, elemId: 0, sd: 12.8 },
    { label: "13", R: 92.51, d: 5.3, nd: 1.48749, elemId: 7, sd: 16.0 },
    { label: "14", R: -68.92, d: 59.576973454065666, nd: 1.0, elemId: 0, sd: 16.0 },
  ],

  /* Patent equation uses a spherical base; therefore K = 0 in LensVisualizer notation. */
  asph: {
    "7A": {
      K: 0,
      A4: -5.88e-7,
      A6: -1.588e-10,
      A8: -2.038e-12,
      A10: 2.54e-16,
      A12: 0,
      A14: 0,
    },
  },

  /* CONSTRAINED_RECONSTRUCTION: rear-focus III-1 translation at the normal/sharp control setting. */
  var: {
    STO: [6.0, 15.007510523201839],
    "12": [19.8, 10.792489476798162],
  },
  varLabels: [
    ["STO", "D9"],
    ["12", "D12"],
  ],

  /* Patent-published normal -> maximum-soft movement; independent of ordinary focus. */
  aberrationControl: {
    label: "SOFT",
    description:
      "US 4,826,301 Example 4: L4 moves rearward 9.20 mm while III-1 moves forward 2.40 mm for image-shift compensation.",
    minLabel: "NORMAL",
    maxLabel: "SOFT",
    var: {
      "6": [0.8, 10.0],
      "8": [17.57, 8.37],
      STO: [6.0, 3.6],
      "12": [19.8, 22.2],
    },
    varLabels: [
      ["6", "D6"],
      ["8", "D8"],
      ["STO", "D9"],
      ["12", "D12"],
    ],
  },

  groups: [
    { text: "I", fromSurface: "1", toSurface: "6" },
    { text: "II", fromSurface: "7A", toSurface: "8" },
    { text: "III-1", fromSurface: "10", toSurface: "12" },
    { text: "III-2", fromSurface: "13", toSurface: "14" },
  ],
  doublets: [{ text: "III-1", fromSurface: "10", toSurface: "12" }],

  closeFocusM: 1.3,
  focusDescription:
    "CONSTRAINED_RECONSTRUCTION: the patent specifies rear focusing by III-1 but no ordinary-focus spacing table. Only the cemented L5+L6 group translates rearward; D9+D12 remains 25.80 mm. The close endpoint is code-solved for Canon's 1.3 m MFD measured from the focal plane, giving 9.007510523 mm travel with the image plane fixed.",

  /* nominalFno sizes the full-open stop; L4 produces the patent's darker sharp-state effective aperture. */
  nominalFno: 2.8,
  fstopSeries: [2.8, 4, 5.6, 8, 11, 16, 22, 32],
  maxFstop: 32,
  apertureBlades: 6,

  /* Default horizontal scaling is retained; this only sets the required vertical fill target. */
  yScFill: 0.35,
} satisfies LensDataInput;

export default LENS_DATA;
