import type { LensDataInput } from "../../types/optics.js";

/**
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║           LENS DATA — CANON EF 8-15mm f/4L FISHEYE USM             ║
 * ╠══════════════════════════════════════════════════════════════════════╣
 * ║  Data source: US 2012/0013996 A1, Numerical Example 1 (Canon).     ║
 * ║  Two-unit negative-positive fisheye zoom for 135 full-frame.       ║
 * ║  14 elements / 11 air-separated groups, 1 aspherical surface.      ║
 * ║  Focus: L12 single-element inner-focus group (surface 9A-10).      ║
 * ║                                                                    ║
 * ║  Zoom variable gaps: D10 and BF.                                   ║
 * ║  Focus variable gaps: D8 and D10.                                  ║
 * ║  D8/D10 close-focus values are paraxial finite-conjugate estimates ║
 * ║  to the manufacturer-published 0.15 m MFD; the patent does not     ║
 * ║  publish close-focus spacing tables for Example 1.                 ║
 * ║                                                                    ║
 * ║  NOTE ON SCALING:                                                  ║
 * ║    No scaling applied. Patent EFLs are 8.05, 11.85, and 15.14 mm.  ║
 * ║                                                                    ║
 * ║  NOTE ON SEMI-DIAMETERS:                                           ║
 * ║    Patent-listed effective diameters were converted to surface     ║
 * ║    semi-diameters by dividing by two.                              ║
 * ║                                                                    ║
 * ║  IMPORTANT: This file describes ONLY the optical design:           ║
 * ║    ✓ Glass elements and surfaces (front element to image plane)    ║
 * ║    ✓ Aperture stop and variable focus/zoom gaps                    ║
 * ║    ✗ DO NOT include: sensor glass, filters, mechanical parts       ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 */

const LENS_DATA = {
  key: "canon-ef-8-15mm-f4l-fisheye-usm",
  maker: "Canon",
  name: "CANON EF 8-15mm f/4 L Fisheye USM",
  subtitle: "US 2012/0013996 A1 Example 1 — Canon / Okumura",
  specs: [
    "14 elements / 11 groups",
    "8-15 mm marketed; 8.05-15.14 mm design",
    "f/4 marketed; F/4.12 patent design",
    "180° circular-to-diagonal fisheye coverage",
    "1 glass-molded aspherical surface",
  ],

  focalLengthMarketing: [8, 15],
  focalLengthDesign: [8.052, 15.141],
  apertureMarketing: 4,
  apertureDesign: 4.12,
  projection: {
    kind: "fisheye-equisolid",
    focalLengthMm: [8.05249, 11.85145, 15.14066],
    fullFieldDeg: [180, 180, 175.5],
    imageCircleMm: [22.3, 33.54, 43.28],
    maxTraceFieldDeg: [90, 90, 87.75],
  },
  lensMounts: ["canon-ef"],
  imageFormat: "135-full-frame",
  patentNumber: "US 2012/0013996 A1",
  patentAuthors: ["Tetsuichirou Okumura"],
  patentAssignees: ["Canon Inc"],
  patentYear: 2012,
  elementCount: 14,
  groupCount: 11,

  elements: [
    {
      id: 1,
      name: "L1",
      label: "Element 1",
      type: "Negative Meniscus",
      nd: 1.804,
      vd: 46.6,
      fl: -31.04,
      glass: "S-LAH65V (OHARA)",
      apd: false,
      role: "Large high-index negative meniscus at the front of L11; establishes the fisheye front-group power and accepts the extreme off-axis bundle.",
    },
    {
      id: 2,
      name: "L2",
      label: "Element 2",
      type: "Negative Meniscus",
      nd: 1.59282,
      vd: 68.6,
      fl: -43.98,
      glass: "FCD505 / FCD515 class (HOYA)",
      apd: "patent",
      dPgF: 0.019,
      apdNote: "Patent Table 4 condition (5) = +0.019 for the first-unit anomalous-dispersion negative lens.",
      role: "Low-dispersion anomalous negative lens in L11; suppresses lateral color generated by the extreme front group.",
    },
    {
      id: 3,
      name: "L3",
      label: "Element 3",
      type: "Biconcave Negative",
      nd: 1.59282,
      vd: 68.6,
      fl: -38.48,
      glass: "FCD505 / FCD515 class (HOYA)",
      apd: "patent",
      dPgF: 0.019,
      apdNote: "Same nd/vd and APD role as L2; patent Table 4 condition (5) = +0.019.",
      role: "Second low-dispersion negative lens in L11; works with L4 to balance first-unit lateral chromatic aberration.",
    },
    {
      id: 4,
      name: "L4",
      label: "Element 4",
      type: "Biconvex Positive",
      nd: 1.80518,
      vd: 25.4,
      fl: 23.82,
      glass: "S-TIH6 (OHARA)",
      apd: false,
      role: "Strong high-dispersion positive lens at the rear of fixed subunit L11; achromatizing partner for the anomalous low-dispersion negative lenses before it.",
    },
    {
      id: 5,
      name: "L5",
      label: "Element 5",
      type: "Neg. Meniscus (1× Asph)",
      nd: 1.85135,
      vd: 40.1,
      fl: -37.94,
      glass: "M-TAFD305 (HOYA)",
      apd: false,
      role: "Single-element L12 inner-focus group. The front surface is the design's sole asphere and moves with the focus group.",
    },
    {
      id: 6,
      name: "L6",
      label: "Element 6",
      type: "Biconvex Positive",
      nd: 1.883,
      vd: 40.8,
      fl: 33.85,
      glass: "S-LAH58 (OHARA) / TAFD33 class",
      apd: false,
      role: "First powered element of L2, immediately behind the supplemental stop; starts the positive relay after the negative front unit.",
    },
    {
      id: 7,
      name: "L7",
      label: "Element 7",
      type: "Biconcave Negative",
      nd: 1.883,
      vd: 40.8,
      fl: -13.62,
      glass: "S-LAH58 (OHARA) / TAFD33 class",
      apd: false,
      role: "Negative member of the first cemented achromat after the aperture stop.",
      cemented: "D1",
    },
    {
      id: 8,
      name: "L8",
      label: "Element 8",
      type: "Biconvex Positive",
      nd: 1.51823,
      vd: 58.9,
      fl: 24.59,
      glass: "S-NSL3 (OHARA)",
      apd: false,
      role: "Positive crown member of D1; pairs with L7 for axial color and spherical correction near the stop.",
      cemented: "D1",
    },
    {
      id: 9,
      name: "L9",
      label: "Element 9",
      type: "Biconvex Positive",
      nd: 1.48749,
      vd: 70.2,
      fl: 24.03,
      glass: "S-FSL5 (OHARA)",
      apd: false,
      role: "Low-index, low-dispersion positive member of the second cemented doublet in L2.",
      cemented: "D2",
    },
    {
      id: 10,
      name: "L10",
      label: "Element 10",
      type: "Negative Meniscus",
      nd: 1.883,
      vd: 40.8,
      fl: -26.4,
      glass: "S-LAH58 (OHARA) / TAFD33 class",
      apd: false,
      role: "High-index negative member of D2; leaves the cemented pair with only weak net positive power.",
      cemented: "D2",
    },
    {
      id: 11,
      name: "L11",
      label: "Element 11",
      type: "Biconvex Positive",
      nd: 1.5927,
      vd: 35.3,
      fl: 35.46,
      glass: "S-FTM16 (OHARA)",
      apd: false,
      role: "Medium-index short-flint positive singlet in the rear relay; contributes positive power and chromatic balance between the doublet groups.",
    },
    {
      id: 12,
      name: "L12",
      label: "Element 12",
      type: "Plano-Concave Negative",
      nd: 1.834,
      vd: 37.2,
      fl: -33.83,
      glass: "S-LAH60V (OHARA)",
      apd: false,
      role: "Negative high-index member of the rear ED cemented pair.",
      cemented: "D3",
    },
    {
      id: 13,
      name: "L13",
      label: "Element 13",
      type: "Biconvex Positive",
      nd: 1.497,
      vd: 81.5,
      fl: 31.96,
      glass: "S-FPL51 (OHARA) / FCD1 class",
      apd: "patent",
      dPgF: 0.028,
      apdNote: "Patent Table 4 condition (6) = +0.028 for the second-unit anomalous-dispersion positive lens.",
      role: "ED positive element and main secondary-spectrum corrector in the rear group; cemented to the dense flint L12.",
      cemented: "D3",
    },
    {
      id: 14,
      name: "L14",
      label: "Element 14",
      type: "Positive Meniscus",
      nd: 1.48749,
      vd: 70.2,
      fl: 178.8,
      glass: "S-FSL5 (OHARA)",
      apd: false,
      role: "Weak rear positive meniscus / field-flattening element before the long back-focus space.",
    },
  ],

  surfaces: [
    { label: "1", R: 59.84, d: 2.5, nd: 1.804, elemId: 1, sd: 30.935 },
    { label: "2", R: 17.282, d: 14.64, nd: 1.0, elemId: 0, sd: 15.5 },
    { label: "3", R: 129.723, d: 1.61, nd: 1.59282, elemId: 2, sd: 16.295 },
    { label: "4", R: 21.61, d: 6.44, nd: 1.0, elemId: 0, sd: 13.695 },
    { label: "5", R: -86.935, d: 1.36, nd: 1.59282, elemId: 3, sd: 13.5 },
    { label: "6", R: 31.102, d: 0.15, nd: 1.0, elemId: 0, sd: 12.92 },
    { label: "7", R: 22.525, d: 7.45, nd: 1.80518, elemId: 4, sd: 13.035 },
    { label: "8", R: -110.226, d: 5.82, nd: 1.0, elemId: 0, sd: 12.36 },
    { label: "9A", R: -31.089, d: 1.2, nd: 1.85135, elemId: 5, sd: 8.9 },
    { label: "10", R: -844.34, d: 20.89, nd: 1.0, elemId: 0, sd: 8.54 },
    { label: "SS", R: 1e15, d: 1.46, nd: 1.0, elemId: 0, sd: 5.13 },
    { label: "12", R: 43.413, d: 1.62, nd: 1.883, elemId: 6, sd: 5.435 },
    { label: "13", R: -94.26, d: 1.85, nd: 1.0, elemId: 0, sd: 5.47 },
    { label: "STO", R: 1e15, d: 1.7, nd: 1.0, elemId: 0, sd: 5.475 },
    { label: "15", R: -19.292, d: 0.75, nd: 1.883, elemId: 7, sd: 5.48 },
    { label: "16", R: 32.493, d: 3.22, nd: 1.51823, elemId: 8, sd: 5.765 },
    { label: "17", R: -20.261, d: 0.2, nd: 1.0, elemId: 0, sd: 6.155 },
    { label: "18", R: 194.716, d: 4.25, nd: 1.48749, elemId: 9, sd: 6.37 },
    { label: "19", R: -12.377, d: 0.8, nd: 1.883, elemId: 10, sd: 6.605 },
    { label: "20", R: -27.182, d: 0.2, nd: 1.0, elemId: 0, sd: 6.98 },
    { label: "21", R: 712.893, d: 3.28, nd: 1.5927, elemId: 11, sd: 7.385 },
    { label: "22", R: -21.62, d: 0.35, nd: 1.0, elemId: 0, sd: 7.935 },
    { label: "23", R: -60941.798, d: 0.93, nd: 1.834, elemId: 12, sd: 8.455 },
    { label: "24", R: 28.231, d: 4.77, nd: 1.497, elemId: 13, sd: 8.8 },
    { label: "25", R: -34.279, d: 0.2, nd: 1.0, elemId: 0, sd: 9.35 },
    { label: "26", R: -80910.795, d: 1.68, nd: 1.48749, elemId: 14, sd: 9.745 },
    { label: "27", R: -87.072, d: 40.25, nd: 1.0, elemId: 0, sd: 9.935 },
  ],

  asph: {
    "9A": {
      K: 0,
      A4: -6.64162e-6,
      A6: 2.58871e-8,
      A8: -8.99837e-10,
      A10: 1.12233e-11,
      A12: -5.07106e-14,
      A14: 0,
    },
  },

  zoomPositions: [8.05, 11.85, 15.14],
  zoomStep: 0.004,
  zoomLabels: ["8 mm", "15 mm"],

  var: {
    "8": [
      [5.82, 2.400255],
      [5.82, 2.600216],
      [5.82, 2.375037],
    ],
    "10": [
      [20.89, 24.309745],
      [9.25, 12.469784],
      [3.89, 7.334963],
    ],
    "27": [
      [40.25, 40.25],
      [49.58, 49.58],
      [57.66, 57.66],
    ],
  },

  varLabels: [
    ["8", "D8 focus gap"],
    ["10", "D10 zoom/focus gap"],
    ["27", "BF"],
  ],

  groups: [
    { text: "L1 negative", fromSurface: "1", toSurface: "10" },
    { text: "L12 focus", fromSurface: "9A", toSurface: "10" },
    { text: "L2 positive", fromSurface: "SS", toSurface: "27" },
  ],

  doublets: [
    { text: "D1", fromSurface: "15", toSurface: "17" },
    { text: "D2", fromSurface: "18", toSurface: "20" },
    { text: "D3", fromSurface: "23", toSurface: "25" },
  ],

  closeFocusM: 0.15,
  focusDescription:
    "Inner focus by translating L12 (element L5, surfaces 9A-10). Close-focus D8/D10 values are paraxial estimates to the official 0.15 m MFD because the patent publishes infinity zoom spacings only.",

  nominalFno: 4,
  fstopSeries: [4, 5.6, 8, 11, 16, 22],
  maxFstop: 22,

  scFill: 0.58,
  yScFill: 0.72,
} satisfies LensDataInput;

export default LENS_DATA;
