import type { LensDataInput } from "../../types/optics.js";

/**
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║        LENS DATA — smc PENTAX-A 645 45mm f/2.8                    ║
 * ╠══════════════════════════════════════════════════════════════════════╣
 * ║  Data source: US 4,487,485 Example 1 (Asahi / Masaharu Hisada).    ║
 * ║  Retrofocus 645-format wide-angle, 9 elements / 8 groups.          ║
 * ║                                                                    ║
 * ║  Patent normalization: F = 100.  All radii, axial spacings,        ║
 * ║  inferred semi-diameters, and back focus are scaled ×0.45 to       ║
 * ║  the 45 mm production focal length.                                ║
 * ║                                                                    ║
 * ║  Focus: unit focus.  The patent publishes only the infinity         ║
 * ║  prescription; close focus is modeled by increasing the final       ║
 * ║  back-focus gap to the thick-lens conjugate solution for a          ║
 * ║  0.45 m object-to-image distance.                                  ║
 * ║                                                                    ║
 * ║  Stop: the patent drawing places the diaphragm in the d8 air gap    ║
 * ║  between L4 and L5 but gives no coordinate; d8 is split evenly      ║
 * ║  around STO for visualization.                                      ║
 * ║                                                                    ║
 * ║  Semi-diameters: not patent-listed.  Values below are inferred      ║
 * ║  from paraxial marginal/chief-ray clearance, the published 67 mm    ║
 * ║  filter thread, and renderer constraints: sd/|R| < 0.90, element    ║
 * ║  SD ratio ≤ 1.25, positive edge thickness, and cross-gap sag        ║
 * ║  intrusion ≤ 90% of gap.                                           ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 */

const LENS_DATA = {
  key: "pentax-645-a-45mm-f28",
  maker: "Pentax",
  name: "PENTAX SMC A 645 45mm f/2.8",
  subtitle: "US 4,487,485 Example 1 — Asahi / Hisada",
  specs: ["45mm f/2.8", "9 elements / 8 groups", "76° on 645 film", "All-spherical", "Unit focus"],

  focalLengthMarketing: 45,
  focalLengthDesign: 45.0006,
  apertureMarketing: 2.8,
  apertureDesign: 2.8,
  lensMounts: ["pentax-645"],
  imageFormat: "645",
  patentYear: 1984,
  elementCount: 9,
  groupCount: 8,
  apertureBlades: 8,

  elements: [
    {
      id: 1,
      name: "L1",
      label: "Element 1",
      type: "Positive Meniscus",
      nd: 1.58913,
      vd: 61.0,
      fl: 320.1,
      glass: "S-BAL35 (OHARA)",
      nC: 1.58619,
      nF: 1.59582,
      ng: 1.60103,
      role: "Weak front collector; moderates oblique ray incidence before the two negative front menisci.",
    },
    {
      id: 2,
      name: "L2",
      label: "Element 2",
      type: "Negative Meniscus",
      nd: 1.48749,
      vd: 70.1,
      fl: -81.0,
      glass: "S-FSL5 (OHARA)",
      nC: 1.48534,
      nF: 1.49228,
      ng: 1.49596,
      role: "First front-group negative meniscus; lower-dispersion glass limits lateral color generated by retrofocus divergence.",
    },
    {
      id: 3,
      name: "L3",
      label: "Element 3",
      type: "Negative Meniscus",
      nd: 1.48749,
      vd: 70.1,
      fl: -66.0,
      glass: "S-FSL5 (OHARA)",
      nC: 1.48534,
      nF: 1.49228,
      ng: 1.49596,
      role: "Second and stronger front-group negative meniscus; completes the F1.2.3 retrofocus diverging group.",
    },
    {
      id: 4,
      name: "L4",
      label: "Element 4",
      type: "Near Plano-Convex Positive",
      nd: 1.72,
      vd: 43.7,
      fl: 79.0,
      glass: "S-LAM52 (OHARA)",
      nC: 1.71511,
      nF: 1.73159,
      ng: 1.74098,
      role: "Thick transitional positive element ahead of the stop; part of the patent's d7+d8+d9 coma-balance condition.",
    },
    {
      id: 5,
      name: "L5",
      label: "Element 5",
      type: "Biconvex Positive",
      nd: 1.72,
      vd: 43.7,
      fl: 44.0,
      glass: "S-LAM52 (OHARA)",
      nC: 1.71511,
      nF: 1.73159,
      ng: 1.74098,
      role: "Primary rear-section converging element; paired in air with L6 for Petzval and chromatic balancing.",
    },
    {
      id: 6,
      name: "L6",
      label: "Element 6",
      type: "Biconcave Negative",
      nd: 1.80518,
      vd: 25.4,
      fl: -38.7,
      glass: "S-TIH6 (OHARA)",
      nC: 1.79611,
      nF: 1.82777,
      ng: 1.84729,
      role: "High-dispersion dense flint; principal Petzval and longitudinal-color balancing element behind L5.",
    },
    {
      id: 7,
      name: "L7",
      label: "Element 7",
      type: "Positive Meniscus",
      nd: 1.83481,
      vd: 42.7,
      fl: 83.4,
      glass: "S-LAH55V (OHARA)",
      nC: 1.82898,
      nF: 1.84852,
      ng: 1.85956,
      role: "High-index relay meniscus; guides the post-stop converging bundle into the final cemented doublet.",
    },
    {
      id: 8,
      name: "L8",
      label: "Element 8",
      type: "Near Plano-Concave Negative",
      nd: 1.80518,
      vd: 25.4,
      fl: -108.6,
      glass: "S-TIH6 (OHARA)",
      nC: 1.79611,
      nF: 1.82777,
      ng: 1.84729,
      cemented: "D1",
      role: "Negative flint member of the rear cemented doublet; fine-tunes chromatic and spherical-aberration residuals.",
    },
    {
      id: 9,
      name: "L9",
      label: "Element 9",
      type: "Biconvex Positive",
      nd: 1.804,
      vd: 46.6,
      fl: 49.7,
      glass: "S-LAH65V (OHARA)",
      nC: 1.79882,
      nF: 1.81608,
      ng: 1.82569,
      cemented: "D1",
      role: "Positive high-index partner in the rear cemented doublet; the cemented group has net positive power.",
    },
  ],

  surfaces: [
    { label: "1", R: 176.08005, d: 3.168, nd: 1.58913, elemId: 1, sd: 21.0 },
    { label: "2", R: 2639.80485, d: 0.099, nd: 1.0, elemId: 0, sd: 21.0 },
    { label: "3", R: 32.2002, d: 1.4985, nd: 1.48749, elemId: 2, sd: 17.0 },
    { label: "4", R: 17.46405, d: 7.6995, nd: 1.0, elemId: 0, sd: 13.8 },
    { label: "5", R: 64.9998, d: 1.3005, nd: 1.48749, elemId: 3, sd: 17.0 },
    { label: "6", R: 21.37995, d: 10.4085, nd: 1.0, elemId: 0, sd: 17.4 },
    { label: "7", R: 57.09105, d: 15.5115, nd: 1.72, elemId: 4, sd: 12.5 },
    { label: "8", R: -13639.24485, d: 1.7505, nd: 1.0, elemId: 0, sd: 12.5 },
    { label: "STO", R: 1e15, d: 1.7505, nd: 1.0, elemId: 0, sd: 11.24 },
    { label: "9", R: 121.5, d: 10.6515, nd: 1.72, elemId: 5, sd: 13.0 },
    { label: "10", R: -41.34015, d: 1.9485, nd: 1.0, elemId: 0, sd: 15.5 },
    { label: "11", R: -78.3891, d: 5.3505, nd: 1.80518, elemId: 6, sd: 15.4 },
    { label: "12", R: 53.1999, d: 2.781, nd: 1.0, elemId: 0, sd: 12.4 },
    { label: "13", R: -76.10985, d: 2.502, nd: 1.83481, elemId: 7, sd: 12.4 },
    { label: "14", R: -36.9, d: 0.099, nd: 1.0, elemId: 0, sd: 15.0 },
    { label: "15", R: -1334.9997, d: 1.2015, nd: 1.80518, elemId: 8, sd: 15.0 },
    { label: "16", R: 93.6, d: 4.068, nd: 1.804, elemId: 9, sd: 16.5 },
    { label: "17", R: -68.43915, d: 62.0115, nd: 1.0, elemId: 0, sd: 17.0 },
  ],

  asph: {},

  var: {
    "17": [62.0115, 68.4912],
  },
  varLabels: [["17", "BF"]],

  groups: [
    { text: "Front retrofocus group", fromSurface: "1", toSurface: "6" },
    { text: "Rear converging group", fromSurface: "7", toSurface: "17" },
  ],
  doublets: [{ text: "D1", fromSurface: "15", toSurface: "17" }],

  closeFocusM: 0.45,
  nominalFno: 2.8,
  fstopSeries: [2.8, 4, 5.6, 8, 11, 16, 22],
  maxFstop: 22,
  scFill: 0.56,
  yScFill: 0.74,
  focusDescription:
    "Unit focus. The patent gives only the infinity prescription; close focus is modeled by increasing the final back-focus gap from 62.0115 mm to 68.4912 mm, matching a 0.45 m object-to-image distance in a thick-lens paraxial solve.",
} satisfies LensDataInput;

export default LENS_DATA;
