import type { LensDataInput } from "../../types/optics.js";

/**
 * ╔════════════════════════════════════════════════════════════════════════════╗
 * ║  LENS DATA — Minolta AF 70-200mm f/2.8 APO G (D) SSM                    ║
 * ╠════════════════════════════════════════════════════════════════════════════╣
 * ║  Source: JP 2004-109559 A, Example 1, Minolta zoom lens system.          ║
 * ║  Patent prescription: f = 71.8 / 105.0 / 195.0 mm, Fno = 2.88.          ║
 * ║  Production correspondence: Minolta/Sony A-mount 70-200mm f/2.8 G SSM.  ║
 * ║                                                                            ║
 * ║  Recalculated EFLs: 71.756668 / 105.008403 / 195.006309 mm.             ║
 * ║  Recalculated BFDs: 51.216172 / 51.216068 / 51.211360 mm.               ║
 * ║  Aperture stop: r24 from the patent table; SD = 18.684 mm from Fno 2.88.║
 * ║                                                                            ║
 * ║  Variable gaps: D9, D18, and D23 are the patent zoom spacings.           ║
 * ║  Focus model: D5/D9 carry an inferred Gr1R objectward focus shift for   ║
 * ║  Sony's official 1.2 m minimum-focus distance; the patent publishes     ║
 * ║  infinity-focus zoom positions only, so the close-focus row is modeled. ║
 * ║                                                                            ║
 * ║  Semi-diameters are not patent-published. They are conservative         ║
 * ║  renderer/mechanical estimates constrained by the 77 mm filter class,   ║
 * ║  edge thickness, element SD ratios, and cross-gap sag-intrusion checks. ║
 * ║  They are not official clear-aperture or production drawing values.     ║
 * ╚════════════════════════════════════════════════════════════════════════════╝
 */

const LENS_DATA = {
  key: "minolta-af-70-200mm-f28-apo-g-d-ssm",
  maker: "Minolta",
  name: "MINOLTA AF 70-200mm f/2.8 APO G (D) SSM",
  subtitle: "JP 2004-109559 A Example 1 — Minolta zoom lens system",
  specs: [
    "Patent Example 1: 19 elements / 15 air-spaced optical clusters",
    "Production class: 70-200mm f/2.8 A-mount",
    "Patent f = 71.8 / 105.0 / 195.0 mm; Fno = 2.88",
    "Four inferred AD/ED elements; all-spherical prescription",
    "Inner focus by Gr1R (L4-L5)",
  ],
  focalLengthMarketing: [70, 200],
  focalLengthDesign: [71.756668, 195.006309],
  apertureMarketing: 2.8,
  apertureDesign: 2.88,
  lensMounts: ["sony-a"],
  imageFormat: "135-full-frame",
  patentNumber: "JP 2004-109559 A",
  patentAuthors: ["Hiroyuki Matsumoto", "Mamoru Terada"],
  patentAssignees: ["Minolta Co Ltd"],
  patentYear: 2004,
  elementCount: 19,
  groupCount: 15,
  zoomPositions: [71.8, 105, 195],
  zoomLabels: ["70 mm", "200 mm"],
  zoomStep: 0.004,
  focusDescription:
    "Inner-focus model: Gr1R (L4-L5) translates objectward for finite focus. Close-focus spacings are a paraxial reconstruction from Sony's 1.2 m official MFD, not a patent-published focus table.",
  elements: [
    {
      id: 1,
      name: "L1",
      label: "Element 1",
      type: "Negative Meniscus",
      nd: 1.62004,
      vd: 36.3,
      fl: -258.77,
      glass: "F2 / S-TIM2 class (620/363; vendor not specified)",
      apd: false,
      cemented: "D1",
      role: "Front negative flint member of the first cemented doublet; balances the very-low-dispersion L2 and moderates front-group spherical and axial-color residuals.",
    },
    {
      id: 2,
      name: "L2",
      label: "Element 2",
      type: "Biconvex Positive ED",
      nd: 1.4931,
      vd: 83.58,
      fl: 199.99,
      glass: "493836 - Minolta AD/ED fluorophosphate-type (nd=1.49310, vd=83.58; catalog unresolved)",
      apd: "inferred",
      apdNote:
        "Sony production literature identifies four ED elements; the patent gives only nd and νd, with no line indices or partial-dispersion data.",
      cemented: "D1",
      role: "First low-dispersion positive element, used in the large fixed front group before the negative zoom variator magnifies residual color.",
    },
    {
      id: 3,
      name: "L3",
      label: "Element 3",
      type: "Positive Meniscus",
      nd: 1.4931,
      vd: 83.58,
      fl: 249.91,
      glass: "493836 - Minolta AD/ED fluorophosphate-type (nd=1.49310, vd=83.58; catalog unresolved)",
      apd: "inferred",
      apdNote: "Second of four inferred AD/ED elements; no patent partial-dispersion data are published.",
      role: "Positive ED/AD continuation of the fixed front collector, preserving axial-color correction while setting the ray geometry entering the focus group.",
    },
    {
      id: 4,
      name: "L4",
      label: "Element 4",
      type: "Negative Meniscus",
      nd: 1.71736,
      vd: 29.5,
      fl: -212.59,
      glass: "E-FD1L (HOYA) / S-TIH1 / N-SF1 class",
      apd: false,
      role: "Negative member of the moving Gr1R inner-focus pair; controls focus-induced spherical and field-curvature variation.",
    },
    {
      id: 5,
      name: "L5",
      label: "Element 5",
      type: "Positive Meniscus",
      nd: 1.6968,
      vd: 56.47,
      fl: 93.41,
      glass: "H-LAK12 (CDGM equivalent; patent 697565)",
      apd: false,
      role: "Primary positive power in the moving Gr1R focus group; paired with L4 to keep the focus unit positive but aberrationally moderated.",
    },
    {
      id: 6,
      name: "L6",
      label: "Element 6",
      type: "Biconcave Negative",
      nd: 1.7545,
      vd: 51.57,
      fl: -52.64,
      glass: "755516 - high-index crown (unresolved)",
      apd: false,
      role: "First negative component of the Gr2 variator; begins the strong negative zoom-power change.",
    },
    {
      id: 7,
      name: "L7",
      label: "Element 7",
      type: "Positive Meniscus",
      nd: 1.84666,
      vd: 23.82,
      fl: 132.86,
      glass: "FDS90 / N-SF57 / S-TIH53 dense-flint class",
      apd: false,
      cemented: "D2",
      role: "Positive high-index dense-flint member of the Gr2 cemented doublet; compactly reshapes variator power and field curvature.",
    },
    {
      id: 8,
      name: "L8",
      label: "Element 8",
      type: "Biconcave Negative",
      nd: 1.67,
      vd: 57.07,
      fl: -37.88,
      glass: "670571 - moderate-index crown (unresolved)",
      apd: false,
      cemented: "D2",
      role: "Negative crown member of the Gr2 doublet; supplies most of the doublet's net negative power while offsetting part of L7 dispersion.",
    },
    {
      id: 9,
      name: "L9",
      label: "Element 9",
      type: "Positive Meniscus",
      nd: 1.84666,
      vd: 23.82,
      fl: 72.04,
      glass: "FDS90 / N-SF57 / S-TIH53 dense-flint class",
      apd: false,
      role: "Positive third component inside the negative Gr2 variator; patent condition f23/f2 bounds its field-curvature moderation.",
    },
    {
      id: 10,
      name: "L10",
      label: "Element 10",
      type: "Negative Meniscus",
      nd: 1.7545,
      vd: 51.57,
      fl: -102.13,
      glass: "755516 - high-index crown (unresolved)",
      apd: false,
      role: "Final negative component of Gr2; controls ray angles before the large variable spacing to Gr3.",
    },
    {
      id: 11,
      name: "L11",
      label: "Element 11",
      type: "Biconvex Positive",
      nd: 1.618,
      vd: 63.39,
      fl: 130.53,
      glass: "N-PSK53A (Schott) / PCD4 / S-PHM52 class",
      apd: false,
      role: "Positive relay element opening Gr3; restores convergence after the negative variator.",
    },
    {
      id: 12,
      name: "L12",
      label: "Element 12",
      type: "Biconvex Positive ED",
      nd: 1.4931,
      vd: 83.58,
      fl: 74.65,
      glass: "493836 - Minolta AD/ED fluorophosphate-type (nd=1.49310, vd=83.58; catalog unresolved)",
      apd: "inferred",
      apdNote: "Third inferred AD/ED element; no patent partial-dispersion data are published.",
      cemented: "D3",
      role: "Positive low-dispersion member of the Gr3 achromatizing doublet, placed after the variator for residual axial and lateral color control.",
    },
    {
      id: 13,
      name: "L13",
      label: "Element 13",
      type: "Negative Meniscus",
      nd: 1.7495,
      vd: 35.04,
      fl: -100.48,
      glass: "E-LAF7 (HOYA) / N-LAF7 class",
      apd: false,
      cemented: "D3",
      role: "High-index flint partner to L12; weakens the doublet's net power and supplies compact chromatic balancing.",
    },
    {
      id: 14,
      name: "L14",
      label: "Element 14",
      type: "Negative Meniscus",
      nd: 1.781,
      vd: 44.55,
      fl: -941.68,
      glass: "781446 - high-index mid-dispersion glass (unresolved)",
      apd: false,
      role: "Very weak negative stop-side element in Gr4f; adjusts marginal-ray correction near the aperture rather than adding large net power.",
    },
    {
      id: 15,
      name: "L15",
      label: "Element 15",
      type: "Biconvex Positive ED",
      nd: 1.4931,
      vd: 83.58,
      fl: 68.74,
      glass: "493836 - Minolta AD/ED fluorophosphate-type (nd=1.49310, vd=83.58; catalog unresolved)",
      apd: "inferred",
      apdNote: "Fourth inferred AD/ED element; no patent partial-dispersion data are published.",
      cemented: "D4",
      role: "Rear positive ED/AD element near the stop; participates in residual color, spherical, and coma correction.",
    },
    {
      id: 16,
      name: "L16",
      label: "Element 16",
      type: "Biconcave Negative",
      nd: 1.62004,
      vd: 36.29,
      fl: -203.56,
      glass: "F2 / S-TIM2 class (620/363; vendor not specified)",
      apd: false,
      cemented: "D4",
      role: "Flint partner to rear ED/AD element L15; completes the positive Gr4f doublet.",
    },
    {
      id: 17,
      name: "L17",
      label: "Element 17",
      type: "Biconvex Positive",
      nd: 1.5927,
      vd: 35.45,
      fl: 125.49,
      glass: "FF5 (HOYA) / S-FTM16 class",
      apd: false,
      role: "Positive first member of the Gr4r rear sub-group; restores convergence before the strong rear negative field-correction element.",
    },
    {
      id: 18,
      name: "L18",
      label: "Element 18",
      type: "Negative Meniscus",
      nd: 1.8061,
      vd: 33.27,
      fl: -57.31,
      glass: "NBFD15-W / NBFD15 (HOYA)",
      apd: false,
      role: "High-index rear negative element; the patent condition fIr2/fIr identifies this as the principal rear field-correction component.",
    },
    {
      id: 19,
      name: "L19",
      label: "Element 19",
      type: "Biconvex Positive",
      nd: 1.717,
      vd: 47.86,
      fl: 94.66,
      glass: "LAF3 / S-LAM3 / N-LAF3 class (close, patent νd=47.86)",
      apd: false,
      role: "Final positive field and back-focus element; helps maintain the SLR-compatible image-side clearance.",
    },
  ],
  surfaces: [
    {
      label: "1",
      R: 479.561,
      d: 3,
      nd: 1.62004,
      elemId: 1,
      sd: 38.5,
    },
    {
      label: "2",
      R: 119.935,
      d: 8.5,
      nd: 1.4931,
      elemId: 2,
      sd: 38.5,
    },
    {
      label: "3",
      R: -541.841,
      d: 0.2,
      nd: 1,
      elemId: 0,
      sd: 38,
    },
    {
      label: "4",
      R: 82.499,
      d: 6.8,
      nd: 1.4931,
      elemId: 3,
      sd: 37.5,
    },
    {
      label: "5",
      R: 242.794,
      d: 13.71,
      nd: 1,
      elemId: 0,
      sd: 37.5,
    },
    {
      label: "6",
      R: 85.355,
      d: 2.5,
      nd: 1.71736,
      elemId: 4,
      sd: 36,
    },
    {
      label: "7",
      R: 54.056,
      d: 0.695,
      nd: 1,
      elemId: 0,
      sd: 29.1,
    },
    {
      label: "8",
      R: 57.664,
      d: 9,
      nd: 1.6968,
      elemId: 5,
      sd: 29.1,
    },
    {
      label: "9",
      R: 473.27,
      d: 1.98,
      nd: 1,
      elemId: 0,
      sd: 31.5,
    },
    {
      label: "10",
      R: -4240.702,
      d: 1.5,
      nd: 1.7545,
      elemId: 6,
      sd: 18.5,
    },
    {
      label: "11",
      R: 40.101,
      d: 5.266,
      nd: 1,
      elemId: 0,
      sd: 16,
    },
    {
      label: "12",
      R: -94.816,
      d: 3.5,
      nd: 1.84666,
      elemId: 7,
      sd: 16,
    },
    {
      label: "13",
      R: -52.32,
      d: 1.5,
      nd: 1.67,
      elemId: 8,
      sd: 16.8,
    },
    {
      label: "14",
      R: 49.848,
      d: 1.613,
      nd: 1,
      elemId: 0,
      sd: 17.5,
    },
    {
      label: "15",
      R: 52.408,
      d: 4.3,
      nd: 1.84666,
      elemId: 9,
      sd: 18.2,
    },
    {
      label: "16",
      R: 358.451,
      d: 3.212,
      nd: 1,
      elemId: 0,
      sd: 16.7,
    },
    {
      label: "17",
      R: -57.162,
      d: 1.5,
      nd: 1.7545,
      elemId: 10,
      sd: 16.7,
    },
    {
      label: "18",
      R: -223.893,
      d: 31.098,
      nd: 1,
      elemId: 0,
      sd: 18.3,
    },
    {
      label: "19",
      R: 1061.154,
      d: 3.7,
      nd: 1.618,
      elemId: 11,
      sd: 20,
    },
    {
      label: "20",
      R: -87.186,
      d: 0.2,
      nd: 1,
      elemId: 0,
      sd: 20,
    },
    {
      label: "21",
      R: 112.872,
      d: 6.605,
      nd: 1.4931,
      elemId: 12,
      sd: 20,
    },
    {
      label: "22",
      R: -53.563,
      d: 1.8,
      nd: 1.7495,
      elemId: 13,
      sd: 20,
    },
    {
      label: "23",
      R: -188.163,
      d: 7.685,
      nd: 1,
      elemId: 0,
      sd: 20,
    },
    {
      label: "STO",
      R: 1e15,
      d: 1.5,
      nd: 1,
      elemId: 0,
      sd: 18.684,
    },
    {
      label: "25",
      R: 44.684,
      d: 4.196,
      nd: 1.781,
      elemId: 14,
      sd: 19.5,
    },
    {
      label: "26",
      R: 40.39,
      d: 0.141,
      nd: 1,
      elemId: 0,
      sd: 19,
    },
    {
      label: "27",
      R: 34.466,
      d: 9.183,
      nd: 1.4931,
      elemId: 15,
      sd: 20,
    },
    {
      label: "28",
      R: -1874.66,
      d: 1.5,
      nd: 1.62004,
      elemId: 16,
      sd: 19.5,
    },
    {
      label: "29",
      R: 135.366,
      d: 33.008,
      nd: 1,
      elemId: 0,
      sd: 19,
    },
    {
      label: "30",
      R: 234.193,
      d: 3.091,
      nd: 1.5927,
      elemId: 17,
      sd: 19,
    },
    {
      label: "31",
      R: -108.454,
      d: 5.703,
      nd: 1,
      elemId: 0,
      sd: 18,
    },
    {
      label: "32",
      R: -28.005,
      d: 2.713,
      nd: 1.8061,
      elemId: 18,
      sd: 18,
    },
    {
      label: "33",
      R: -74.199,
      d: 2.104,
      nd: 1,
      elemId: 0,
      sd: 20,
    },
    {
      label: "34",
      R: 153.847,
      d: 4.288,
      nd: 1.717,
      elemId: 19,
      sd: 21.5,
    },
    {
      label: "35",
      R: -120.026,
      d: 51.216172,
      nd: 1,
      elemId: 0,
      sd: 21.5,
    },
  ],
  asph: {},
  var: {
    "5": [
      [13.71, 0.914722],
      [13.71, 0.914737],
      [13.71, 0.914787],
    ],
    "9": [
      [1.98, 14.775278],
      [15.965, 28.760263],
      [29.959, 42.754213],
    ],
    "18": [
      [31.098, 31.098],
      [23.491, 23.491],
      [2.8, 2.8],
    ],
    "23": [
      [7.685, 7.685],
      [1.306, 1.306],
      [8.004, 8.004],
    ],
    "35": [
      [51.216172, 51.216172],
      [51.216068, 51.216068],
      [51.21136, 51.21136],
    ],
  },
  varLabels: [
    ["5", "IF front"],
    ["9", "IF rear / D9"],
    ["18", "D18"],
    ["23", "D23"],
    ["35", "BF"],
  ],
  groups: [
    {
      text: "Gr1F",
      fromSurface: "1",
      toSurface: "5",
    },
    {
      text: "Gr1R / IF",
      fromSurface: "6",
      toSurface: "9",
    },
    {
      text: "Gr2",
      fromSurface: "10",
      toSurface: "18",
    },
    {
      text: "Gr3",
      fromSurface: "19",
      toSurface: "23",
    },
    {
      text: "Gr4",
      fromSurface: "STO",
      toSurface: "35",
    },
  ],
  doublets: [
    {
      text: "D1",
      fromSurface: "1",
      toSurface: "3",
    },
    {
      text: "D2",
      fromSurface: "12",
      toSurface: "14",
    },
    {
      text: "D3",
      fromSurface: "21",
      toSurface: "23",
    },
    {
      text: "D4",
      fromSurface: "27",
      toSurface: "29",
    },
  ],
  closeFocusM: 1.2,
  nominalFno: 2.8,
  fstopSeries: [2.8, 4, 5.6, 8, 11, 16, 22, 32],
  maxFstop: 32,
  scFill: 0.72,
  yScFill: 0.5,
} satisfies LensDataInput;

export default LENS_DATA;
