import { describe, it, expect } from "vitest";
import { allMakerSlugs } from "../src/utils/lensMetadata.js";
import buildMeta from "../src/generated/build-metadata.json";

/**
 * These tests verify that the build-time metadata (generated by
 * generate-build-metadata.mjs) stays in sync with the runtime code.
 * They require `npm run generate:metadata` to have been run first.
 */
describe("build-route-sync", () => {
  it("every lens key has freshness metadata", () => {
    const freshness = buildMeta.lensFreshness as Record<string, { publishedOn: string; lastModified: string }>;

    for (const key of buildMeta.lensKeys) {
      expect(freshness[key]).toBeDefined();
      expect(freshness[key].publishedOn).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(freshness[key].lastModified).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });

  it("every shipped maker slug is registered in the runtime prefix table", () => {
    /* Runtime prefixes may include makers that have no lenses yet (entries are
       seeded ahead of lens additions), so we only assert the one-way subset:
       every maker that actually appears in build metadata must be registered
       at runtime. The reverse direction is allowed to differ. */
    const runtimeSlugs = new Set(allMakerSlugs());
    for (const slug of buildMeta.makerSlugs) {
      expect(runtimeSlugs.has(slug), `build slug "${slug}" missing from runtime MAKER_PREFIXES`).toBe(true);
    }
  });

  it("routes array is non-empty and includes expected static routes", () => {
    const routes = buildMeta.routes;

    expect(routes.length).toBeGreaterThan(0);
    expect(routes).toContain("/");
    expect(routes).toContain("/lenses");
    expect(routes).toContain("/makers");
    expect(routes).toContain("/articles");
  });

  it("lensKeys array matches routes with /lens/ prefix", () => {
    const lensKeys = buildMeta.lensKeys;
    const lensRoutes = buildMeta.routes.filter((r: string) => r.startsWith("/lens/"));

    expect(lensRoutes.length).toBe(lensKeys.length);
    for (const key of lensKeys) {
      expect(lensRoutes).toContain(`/lens/${key}`);
    }
  });

  it("article slugs match routes with /articles/ prefix", () => {
    const articleSlugs = buildMeta.articles.map((a: { slug: string }) => a.slug);
    const articleRoutes = buildMeta.routes.filter((r: string) => r.startsWith("/articles/"));

    expect(articleRoutes.length).toBe(articleSlugs.length);
    for (const slug of articleSlugs) {
      expect(articleRoutes).toContain(`/articles/${slug}`);
    }
  });

  it("articles include published and modified dates", () => {
    for (const article of buildMeta.articles as { publishedOn: string; lastModified: string }[]) {
      expect(article.publishedOn).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(article.lastModified).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });

  it("makerSlugs match routes with /makers/ prefix", () => {
    const makerRoutes = buildMeta.routes.filter((r: string) => r.startsWith("/makers/"));

    expect(makerRoutes.length).toBe(buildMeta.makerSlugs.length);
    for (const slug of buildMeta.makerSlugs) {
      expect(makerRoutes).toContain(`/makers/${slug}`);
    }
  });

  it("every prerendered route has freshness metadata", () => {
    const routeFreshness = buildMeta.routeFreshness as Record<string, { publishedOn: string; lastModified: string }>;

    for (const route of buildMeta.routes as string[]) {
      expect(routeFreshness[route]).toBeDefined();
      expect(routeFreshness[route].publishedOn).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(routeFreshness[route].lastModified).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });
});
